oscal-compass/compliance-trestle

- .github/workflows/python-test.yml
> Fix/semantic release - fixing semantic release issues with github actions.

- codecov.yml
> Adding codecov yaml

- .github/workflows/semantic-release.yml
- codecov.yml
Reverting to a more understandable version of semantic release.
> fix: Reverted semantic release to "hand coded" form.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/new_collaborator.md
Updates issue templates. 
closes #29
> fix: Issue templates are not being picked up by github.

- setup.cfg
Fixed error caused when running pip install.
closes #44
Signed-off-by: Bruno <brunomar@au1.ibm.com>
> fix: fix conflict between attrs and markdown-it-py

- tests/trestle/core/parser_test.py
- tests/trestle/parsing/parsing_test.py
- trestle/core/parser.py
Wrap for input / output was incorrectly handling cases where the object name had a hyphen in it. This function corrects this behavior and adds unit tests to cover this issue.
closes: #75
> fix: Correct wrap input / output functions.

- .github/workflows/python-push.yml
Updated pipeline to separate out builds. Also added nightly builds. Still under testing. 
closes #82
> Separated push and PR actions

- tests/trestle/core/base_model_test.py
- trestle/core/base_model.py
- trestle/core/utils.py
Refactor of IO and copy utilities for OscalBaseModel
closes #62 #76 
opens #85
> Created updated IO and object copy methods

- README.md
Added extra documentation to cover `target`.
closes: #16
> Updated documentation with a short description of target

- trestle/oscal/profile.py
- trestle/oscal/ssp.py
This is a hotfix as the profile object that is currently in trunk has an issue with the `parameter-settings` schema object. I've opened an issue to correct the underlying issue here: #95. This just fixes the current instanciation of the issue until our next release.
> fix: Corrected typing of parameter-settings in profile.

- .pre-commit-config.yaml
In issuing a hotfix we encountered a bug in the CICD pipeline which caused the release to fail (see here: #101). This corrects this mistake to enable the original hotfix release.
> fix: Correcting missed pre-commit change that broke build process.

- CONTRIBUTING.md
- README.md
- \[ x\] My code follows the code style of this project.
- \[ x\] My change requires a change to the documentation.
- \[ x\] I have updated the documentation accordingly.
Grammar and readbility improvements to README and CONTRIBUTING
> Edit and proofread README and CONTRIBUTING

- tests/trestle/core/models/element_path_test.py
- tests/trestle/core/models/element_test.py
- tests/trestle/core/models/remove_action_test.py
- tests/trestle/core/models/update_action_test.py
- trestle/core/commands/cmd_utils.py
- trestle/core/models/elements.py
- \[x\] Breaking change (fix or feature that would cause existing functionality to change)
> Support parent path and root model for ElementPath

- tests/trestle/core/utils_test.py
- trestle/core/commands/cmd_utils.py
- trestle/core/commands/merge.py
- trestle/core/utils.py
> Add unit tests for some utils functions and rename a few of those functions

- README.md
Updated the documentation to reflect the alpha status of the project.
> docs: Update readme to reflect alpha status.

- trestle/core/commands/split.py
> Use get_stripped_contextual_model

- tests/trestle/core/models/create_path_action_test.py
- trestle/core/models/actions.py
> CreatePathAction should have an option to clean the content of a file if it exists #159

- tests/trestle/utils/fs_test.py
- trestle/utils/fs.py
> refactor: adjust contextual helper methods for new structure

- trestle/core/commands/merge.py
- fix "compilation" issues on merge.py module.
> fix: reference to inexistent function

- README.md
…rmats
This is adding documentation to the fact that only `json` and `yaml` are currently supported.
links to issues  #70 #178 #177
> docs: Updated readme to document format support

- tests/trestle/core/commands/cmd_utils_test.py
- trestle/core/commands/cmd_utils.py
> fix: support contextual element path like groups.* during split

- trestle/__init__.py
> fix: Versioning tag was malformed.

- trestle/__init__.py
Hotfix to correct malformed version tag.
> fix: Versioning tag was malformed. (#199)

- scripts/fix_any.py
- trestle/oscal/assessment_results.py
- trestle/oscal/ssp.py
New changes to fixany.py to prevent generation of GroupItem empty classes and fix corresponding Union[]s with conlist.
> fix to issue_218: handle anomalous oscal GroupItems

- tests/trestle/core/utils_test.py
- trestle/core/base_model.py
- trestle/core/const.py
- trestle/core/models/actions.py
- trestle/core/models/file_content_type.py
- trestle/core/utils.py
- trestle/utils/fs.py
> fix: Refactor to adopt FileContentType consistently

- tests/trestle/core/commands/init_test.py
- trestle/cli.py
- trestle/core/commands/init.py
- trestle/core/parser.py
- trestle/oscal/__init__.py
A number of incremental improvements in typing and return codes.
> fix: Improvements in typing and return codes.

- trestle/__main__.py
Hotfix for missing `__main__.py` module.
> Added missing main file for running as a module.

- Makefile
- codecov.yml
- tests/trestle/conftest.py
- tests/trestle/core/commands/create_test.py
- tests/trestle/core/generator_test.py
- tests/trestle/core/utils_test.py
- trestle/__main__.py
- trestle/core/commands/add.py
- trestle/core/commands/create.py
- trestle/core/generators.py
- trestle/core/utils.py
- trestle/oscal/__init__.py
- trestle/oscal/ssp.py
Completed first pass implementation of trestle create. Additional functionality (like default splits) could be added, however, have not been yet.
> Trestle create command

- tests/trestle/core/commands/import__test.py
- trestle/core/commands/import_.py
> Trestle import and unit testing

- .github/ISSUE_TEMPLATE/new_collaborator.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/codeql-analysis.yml
- .github/workflows/python-push.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- codecov.yml
- \[x\] Breaking change (fix or feature that would cause existing functionality to change)
Fixes for P.C. reasons. New main branch will need to be created and master will need to be deleted at some stage.
> Remove references to master branch and run releases off of "main"

- .github/workflows/python-push.yml
- .github/workflows/python-test.yml
- setup.cfg
- tests/trestle/cli_test.py
- tests/trestle/core/base_model_test.py
- tests/trestle/core/err_test.py
- tests/trestle/core/generator_test.py
- tests/trestle/core/parser_test.py
- tests/trestle/core/utils_test.py
- tests/trestle/parsing/parsing_test.py
- tests/trestle/utils/fs_test.py
- tests/trestle/utils/trash_test.py
- trestle/core/commands/create.py
- trestle/core/commands/remove.py
- trestle/core/generators.py
- trestle/core/parser.py
- trestle/core/utils.py
This is a bit of a grab bag of issues which are being solved. Please consider a draft at this stage.
> Misc cleanups of code for typing, unsafe functions, and other issues.

- trestle/__init__.py
> feat: Force update of version for release

- setup.cfg
- \x \] All new and existing tests passed.
Corrects the branch targeted by semantic release to ensure releases occur properly.
> Corrected semantic release behaviour.

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/python-push.yml
Ensure all version tags are up to date.
closes #293
> chore: Ensure develop is correctly updated after a release. 

- tests/trestle/core/remote/cache_test.py
- trestle/core/remote/cache.py
Just adds local fetcher functionality from an absolute path, with a test for it.
> LocalFetcher can now refresh cache from file:/// or absolute path source

- tests/trestle/core/base_model_test.py
- tests/trestle/main_test.py
- trestle/core/commands/cmd_utils.py
Test coverage in the last PR slipped when compared against main. This PR is a small edit to add back some test coverage which dropped due to changes in the code base. It also adds test coverage of '__name__' == __main__ statements as …
> Extra unit tests and cleanup to close more significant gaps

- .github/workflows/python-push.yml
Note: Alternative techniques may be required, however, with devops integration it must be tested live.
> fix: Corrected branch for mkdocs deploy.

- .github/workflows/python-push.yml
Note: Alternative techniques may be required, however, with devops integration it must be tested live.
> fix: Corrected branch for mkdocs deploy. (#304)

- docs/cli.md
- tests/data/split_merge/README.md
Grammar and style tweaks in cli.md, plus fixed misspellings in split_merge doc.
> Fix typos and grammar in cli and misspelling in split_merge docs

- tests/trestle/utils/fs_test.py
- trestle/core/commands/merge.py
- trestle/utils/fs.py
Remove hard coded json file extension from merge cmd.
closes #275
> Parameterised file extension in merge cmd.

- mkdocs.yml
Current website has a bad link which has been corrected. This closes #313
> Corrected bad link for website homepage.

- scripts/website_automation.py
Running `make `docs-serve` on linux (Red HAt 7.9) fails.`
LICENSE file is all caps.
Closes #329
> fix 'make docs-serve' on linux (Red Hat 7.9)

- tests/trestle/docs-serve/website_automation_test.py
Unit test for website boot and usability.
Closes #337
> unit test: website boots and is usable.

- trestle/core/duplicates_validator.py
Issue #301.  Validate duplicates now loads distributed files.
Small and local change to code.
> validate duplicates now loads distributed models

- tests/trestle/core/commands/validate_test.py
- tests/trestle/utils/fs_test.py
- trestle/core/commands/validate.py
- trestle/core/duplicates_validator.py
Wrap validate in try block so no exceptions occur at command line interface.  Increase test coverage of validate and fs.
> Wrap validate in try block to catch exceptions.  Increase test coverage.

- tests/trestle/docs-serve/website_automation_test.py
Lou's fix to website automation test not working on windows.
> Lou's fix to website automation test on windows

- setup.cfg
Constrained pydantic version and cleaned up setup.cfg to minimise unneccessary.
> Fix: Dependency issues

- trestle/core/base_model.py
- trestle/utils/load_distributed.py
Added utilities to deal with Collection types around OscalBaseModel.
> Draft: feat: added collection utilities.

- codecov.yml
- \[ \] All commits are signed-off.
Experimenting with relaxing codecov requirements. As this is CICD we may have to weak this further.
> chore: Adjust codecov to allow for some wiggle room.

- scripts/tanium_transform_script.py
- trestle/transforms/__init__.py
- trestle/transforms/implementations/__init__.py
- trestle/transforms/implementations/tanium.py
- trestle/transforms/utils/__init__.py
The current method of registering with the transformer factory was flawed. Corrected and added an example script for using the transformer factory.
> fix:Corrected transforms behaviour and added example script

- scripts/tanium_transform_script.py
- trestle/transforms/__init__.py
- trestle/transforms/implementations/__init__.py
- trestle/transforms/implementations/tanium.py
- trestle/transforms/utils/__init__.py
Release to correct broken behaviour and allow partner development
> Minor release: Fix behaviour of trestle transforms

- .pre-commit-config.yaml
> fix:Chore update pre-commit formatting

- docs/tutorials/python_trestle_setup.md
- docs/tutorials/trestle_sample_workflow.md
- tests/trestle/core/commands/import__test.py
- tests/trestle/core/commands/merge_test.py
- tests/trestle/utils/fs_test.py
- trestle/core/base_model.py
- trestle/core/commands/import_.py
- trestle/core/commands/merge.py
- trestle/core/models/actions.py
- trestle/core/models/elements.py
- trestle/utils/fs.py
- trestle/utils/log.py
> Release to main: essential fixes to file IO

- docs/tutorials/task.tanuim-to-oscal/transformation.md
- tests/data/tasks/tanium/output/Tanium.oscal.2020.json
- tests/data/tasks/tanium/output/Tanium.oscal.json
- trestle/transforms/implementations/tanium.py
- trestle/transforms/utils/tanium_helper.py
- \[x] My change requires a change to the documentation.
Enhancements to tanium transformer for scc
> Release: enhancements to tanium transformer for scc

- docs/tutorials/task.tanuim-to-oscal/transformation.md
- tests/data/tasks/tanium/output/Tanium.oscal.2020.json
- tests/data/tasks/tanium/output/Tanium.oscal.json
- trestle/transforms/implementations/tanium.py
- trestle/transforms/utils/tanium_helper.py
Reverts IBM/compliance-trestle#494
reverting changes as didn't put fix;chores while merging and it didin't release
> Revert "Release: enhancements to tanium transformer for scc"

- docs/tutorials/task.tanuim-to-oscal/transformation.md
- tests/data/tasks/tanium/output/Tanium.oscal.2020.json
- tests/data/tasks/tanium/output/Tanium.oscal.json
- trestle/transforms/implementations/tanium.py
- trestle/transforms/utils/tanium_helper.py
- \[x] My change requires a change to the documentation.
> Release: tanium updates for scc, 2

- docs/tutorials/task.tanuim-to-oscal/transformation.md
- tests/data/tasks/tanium/output/Tanium.oscal.2020.json
- tests/data/tasks/tanium/output/Tanium.oscal.json
- trestle/transforms/implementations/tanium.py
- trestle/transforms/utils/tanium_helper.py
- \[x] My change requires a change to the documentation.
Add the needed timestamp as property value in tanium transformer
> fix: Add timestamp to tanium-to-oscal transformer

- setup.cfg
Signed-off-by: FrankSuits <frankst@au1.ibm.com>
Upgrade pydantic to 1.8.2 for security issue
> upgrade pydantic to 1.8.2 for security issue

- trestle/core/all_validator.py
This is a minimal PR to trigger the DevOps pipeline for testing.
> chore: Updated some docs to trigger a PR

- .github/workflows/trestle-develop-automerge.yml
- trestle/core/utils.py
Small set of documentation updates to trigger a PR workflow.
> docs: Small set of document updates

- trestle/core/object_factory.py
> docs: Additional documentation.

- trestle/core/ncname_validator.py
> docs: More google style doc strings

- tests/trestle/core/commands/split_test.py
- trestle/core/models/elements.py
Signed-off-by: FrankSuits <frankst@au1.ibm.com>
Better handling of lists and dicts in split
Issue #483 
Issue #548
> fix: errors in Split for roles and compdefs (lists and dicts)

- .github/workflows/trestle-develop-automerge.yml
Reducing permissions of CICD process to protect branches properly.
> fix: CICD cleanup to prevent admin 

- tests/trestle/core/generator_test.py
- trestle/core/const.py
- trestle/core/generators.py
- trestle/oscal/poam.py
> fix: Consolidate UUID sample and sample fix for POAM forward refs.

- tests/trestle/core/generator_test.py
- trestle/core/generators.py
> fix: Correct generator behaviour

- .github/workflows/python-push.yml
- .github/workflows/python-test.yml
This will take effect after this is on develop branch.
> fix: Ensure line endings do not change

- Makefile
- scripts/oscal_normalize.py
- tests/trestle/core/commands/add_test.py
- tests/trestle/core/validator_helper_test.py
- tests/trestle/utils/fs_test.py
- tests/trestle/utils/md_writer_test.py
- trestle/core/base_model.py
- trestle/core/commands/author/ssp.py
- trestle/oscal/assessment_plan.py
- trestle/oscal/assessment_results.py
- trestle/oscal/common.py
- trestle/oscal/component.py
- trestle/oscal/poam.py
- trestle/oscal/profile.py
- trestle/oscal/ssp.py
- trestle/utils/md_writer.py
Signed-off-by: FrankSuits <frankst@au1.ibm.com>
Fixed duplicate classes in two oscal files
Reordered classes for deterministic generation
Updated some tests to oscal 1.0.0
Improved md output in ssp generate
> fix: duplicate oscal classes and reordered.  oscal_write line ending

- tests/trestle/core/commands/author/ssp_test.py
- tests/trestle/core/commands/split_test.py
- tests/trestle/core/commands/validate_test.py
- tests/trestle/core/models/element_test.py
- tests/trestle/core/utils_test.py
- tests/trestle/core/validator_helper_test.py
- trestle/core/commands/author/ssp.py
- trestle/core/commands/split.py
- trestle/core/commands/validate.py
- trestle/core/models/elements.py
- trestle/core/utils.py
- trestle/core/validator_helper.py
Added test coverage
fixed split_too_fine
removed dict queries that aren't needed
> fix: boost coverage fix split_too_fine

- .github/ISSUE_TEMPLATE/new_collaborator.md
- .github/PULL_REQUEST_TEMPLATE.md
- .pre-commit-config.yaml
Added `mdformat-gfm` which removes some unnecessary mess made by mdformat.
> fix: Add gfm support for mdformat

- .pre-commit-config.yaml
- scripts/gen_oscal.py
- scripts/oscal_normalize.py
- tests/trestle/tasks/tanium_to_oscal_test.py
- trestle/core/base_model.py
- trestle/core/draw_io.py
- trestle/core/validator_helper.py
- trestle/tasks/osco_to_oscal.py
- trestle/tasks/tanium_to_oscal.py
- trestle/transforms/utils/osco_helper.py
Cleans up linting including identifying files which had not been linted.
> fix: Cleanup and enhancement of linting.

- .github/workflows/python-test.yml
- .gitignore
- Makefile
- setup.cfg
This allows pytest to run in parallel and minimises coverage generation. It should result in 2-4 times faster depending on the setup.
> chore: Improving testing performance in CICD

- docs/demonstrations-content.md
- tests/trestle/core/commands/import__test.py
- trestle/core/base_model.py
- trestle/core/models/elements.py
Default serialisation using python's built in json library assumes that you want to use ascii. Overrode this functionality and did some updates of documentation.
> fix: Updated documentation and ensure utf-8 is supported properly by json serialization

- mkdocs.yml
Adding google analytics to deployed website.
> chore: Adding google analytics to website

- docs/cli.md
- docs/specifications/caching_spec.md
- tests/test_utils.py
- tests/trestle/core/commands/add_test.py
- tests/trestle/core/commands/create_test.py
- tests/trestle/core/commands/import__test.py
- tests/trestle/core/commands/partial_object_validate_test.py
- trestle/core/commands/add.py
- trestle/core/commands/create.py
- trestle/core/const.py
…estle add and trestle create
**CURRENTLY DRAFT**
Partially complete: #673 
Closes: #692
> feat: Adding rich model generation to trestle add and trestle create.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/proposed_change.md
This just cleans up the templates a little. I just wanted to remove some of the unnecessary fields.
Closes #698
> chore: Clean up issue templates.

- trestle/core/commands/assemble.py
This cleans up the assemble command to reduce total LoC while maintaining the same functionality. 
Closes #706
> fix: Cleanup assemble command to reduce unnecessary code.

- scripts/oscal_normalize.py
- trestle/oscal/assessment_plan.py
- trestle/oscal/assessment_results.py
- trestle/oscal/catalog.py
- trestle/oscal/common.py
- trestle/oscal/component.py
- trestle/oscal/poam.py
- trestle/oscal/profile.py
- trestle/oscal/ssp.py
Another manual update of oscal using make develop and make gen-oscal
dmcg is now at version 0.11.12
Only change needed was to import Pydantic Extra in all oscal model .py files
This also did the automatic replacement for IncludeAll in files.
> chore: regen oscal with new datamodel-codegen and make develop

- mkdocs.yml
- tests/test_utils.py
- tests/trestle/core/commands/add_test.py
- tests/trestle/core/commands/assemble_test.py
- tests/trestle/core/commands/cmd_utils_test.py
- tests/trestle/core/commands/describe_test.py
- tests/trestle/core/commands/merge_test.py
- tests/trestle/core/commands/replicate_test.py
- tests/trestle/core/commands/split_test.py
- tests/trestle/utils/fs_test.py
- tests/trestle/utils/load_distributed_test.py
- trestle/core/commands/add.py
- trestle/core/commands/assemble.py
- trestle/core/commands/cmd_utils.py
- trestle/core/commands/describe.py
- trestle/core/commands/merge.py
- trestle/core/commands/remove.py
- trestle/core/commands/replicate.py
- trestle/core/commands/split.py
- trestle/core/repository.py
- trestle/core/validator.py
- trestle/utils/fs.py
- trestle/utils/load_distributed.py
- [] New feature (non-breaking change which adds functionality)
I need to write some new tests for the `trestle.utils.fs` module but otherwise this should be good to go. 
This PR isolates CWD calls which has the downside that cwd needs to be explicitly passed more, however, removes some bugs that impacted the `trestle.core.repository`
> fix: Refactor underlying methods to isolate calls to Path.cwd()

- tests/data/tasks/profile-to-osco/input/profile-disable.json
- tests/data/tasks/profile-to-osco/output-disable/osco-profile.yaml
- tests/data/tasks/profile-to-osco/output-set/osco-profile.yaml
- tests/data/tasks/profile-to-osco/output/osco-profile.yaml
- tests/data/tasks/profile-to-osco/profile-to-osco-disable.config
- tests/trestle/tasks/profile_to_osco_test.py
- trestle/tasks/profile_to_osco.py
- trestle/transforms/implementations/osco.py
- add rationales to produced yaml
- add disableRules to produced yaml
- use metadata.props for produced yaml extends and metadata.name
- update and add test cases for 100% coverage
> feat: oscal-profile-to-osco-yaml-rev2

- docs/cli.md
- docs/tutorials/trestle_sample_workflow.md
- tests/trestle/core/commands/author/ssp_test.py
- tests/trestle/core/commands/import__test.py
- tests/trestle/core/commands/init_test.py
- tests/trestle/core/remote/cache_test.py
- trestle/core/commands/import_.py
- trestle/core/commands/init.py
- trestle/core/const.py
- trestle/core/models/elements.py
- trestle/core/models/file_content_type.py
- trestle/core/parser.py
- trestle/core/remote/cache.py
- trestle/utils/fs.py
Import now uses cache, and the cache system is generalized to handle relative paths.
> feat: import cache

- README.md
Add link from make README.md to compliance-trestle-demos project.
> feat: add link to compliance-trestle demos in main README.md.

- docs/api_reference/trestle.tasks.profile_to_osco.md
- tests/functionality/__init__.py
- tests/functionality/example_test.py
- tests/functionality/pathlib_test.py
- tests/trestle/core/commands/merge_test.py
- tests/trestle/core/draw_io_test.py
- trestle/core/commands/merge.py
- trestle/core/draw_io.py
- trestle/core/repository.py
This refines merge behaviour across platforms which improves performance on windows for python versions which are not the latest bugfixes.
Also adds some functionality to the drawio module to deal with 'flattened' metadata.
Closes: #719
> fix: Correct merge (including repository functionality) and improve merge cwd handling.

- tests/data/tasks/osco/output-compressed/ssg-rhel7-ds-cis-111.222.333.444-pod.oscal.json
- tests/data/tasks/osco/output-configmaps/configmaps.oscal.json
- tests/data/tasks/osco/output-fetcher/cluster_resource.oscal.json
- tests/data/tasks/osco/output-xml-ocp4/ocp4-check-result.oscal.json
- tests/data/tasks/osco/output/ssg-ocp4-ds-cis-111.222.333.444-pod.oscal.json
- trestle/transforms/utils/osco_helper.py
> fix: Update OCP compliance operator transform to use classes expected by IBM SCC.

- setup.cfg
Release PR to cover emergency fixes.
> chore: Trestle release

- trestle/core/commands/replicate.py
A small refactoring of the replicate command from subcommands to the CLI choices. 
Closes #738
> refactor: Refactor replicate command to use CLI choices

- tests/test_utils.py
- trestle/core/commands/init.py
- trestle/core/utils.py
- [?] Bug fix (non-breaking change which fixes an issue)
Clean up all BaseExceptions code smells throughout the project.
Related to https://github.com/IBM/compliance-trestle/issues/779
> chore: Remove BaseExceptions code smells

- tests/conftest.py
- tests/trestle/core/profile_resolver_test.py
- trestle/core/control_io.py
- trestle/core/profile_resolver.py
Added support for different merge methods in profile resolver.
> fix: profile merge support

- tests/trestle/core/commands/author/catalog_test.py
- tests/trestle/core/commands/author/profile_test.py
- tests/trestle/core/commands/author/ssp_test.py
- trestle/core/commands/author/catalog.py
- trestle/core/commands/author/profile.py
- trestle/core/commands/author/ssp.py
- trestle/core/const.py
Added support for yaml header insertion for profile and catalog generate
Cleaned up and added tests
> feat: add yaml header output for profile and catalog generate

- tests/conftest.py
- tests/data/json/simple_test_profile.json
- tests/data/json/test_profile_a.json
- tests/data/json/test_profile_b.json
- tests/data/json/test_profile_e.json
- tests/data/json/test_profile_f.json
- tests/test_utils.py
- tests/trestle/core/commands/author/catalog_test.py
- tests/trestle/core/commands/author/ssp_test.py
- tests/trestle/core/commands/import__test.py
- tests/trestle/core/profile_resolver_test.py
- trestle/core/catalog_interface.py
- trestle/core/commands/author/catalog.py
- trestle/core/profile_resolver.py
- trestle/core/utils.py
Fuller support of merge behavior in profile_resolver
New utilities none_if_empty and as_list for handling nones and empty lists
> fix: enhance profile resolver merge abilities

- trestle/core/control_io.py
- trestle/core/profile_resolver.py
- Minor fixes for SSP functionality for reliability.
> Bug fix release

- trestle/core/commands/author/headers.py
Fix recurse flag in headers validation
> fix: Fix headers recurse flag

- trestle/tasks/cis_to_component_definition.py
Fix 2 bugs found when authoring demo of task cis-to-component-definition.
Closes #855.
> fix: 2 bugs in task cis-to-component-definition

- tests/trestle/core/commands/author/catalog_test.py
- tests/trestle/core/commands/author/profile_test.py
- tests/trestle/core/commands/author/ssp_test.py
- tests/trestle/core/control_io_test.py
- tests/trestle/utils/md_writer_test.py
- trestle/core/catalog_interface.py
- trestle/core/commands/author/catalog.py
- trestle/core/commands/author/headers.py
- trestle/core/commands/author/profile.py
- trestle/core/commands/author/ssp.py
- trestle/core/const.py
- trestle/core/control_io.py
- trestle/core/markdown/md_writer.py
- trestle/tasks/cis_to_component_definition.py
- Fixes critical bugs in the trestle author command
- Additional feature of `--header-merge` flag for trestle author *-generate.
> Trestle release

- docs/api_reference/trestle.core.commands.author.versioning.template_versioning.md
- docs/api_reference/trestle.core.markdown.markdown_const.md
- docs/api_reference/trestle.core.markdown.md_writer.md
- docs/api_reference/trestle.tasks.cis_to_component_definition.md
- docs/api_reference/trestle.transforms.utils.tanium_helper.md
- docs/api_reference/trestle.utils.md_writer.md
- mkdocs.yml
- Corrected build problems with mkdocs
> fix: Correcting mkdocs

- trestle/core/commands/author/docs.py
Fix default template version for docs
> fix: Fix instance version

- tests/data/tasks/profile-to-osco/output-disable/osco-profile.yaml
- tests/data/tasks/profile-to-osco/output-set/osco-profile.yaml
- tests/data/tasks/profile-to-osco/output/osco-profile.yaml
- trestle/transforms/implementations/osco.py
Some version(s) of OSCO require spec.description in the yaml.
> fix: add spec.description to produced yaml

- trestle/transforms/utils/osco_helper.py
Fix task osco-to-oscal console display - remove: `results {}`
> fix: remove results {} from osco-to-oscal console display

- .github/workflows/conventional-pr.yml
- This is correcting a break that occurred (and may require some iteration to fix). 
> fix: Incorrect behaviour of lint PR.

- trestle/core/commands/author/ssp.py
- trestle/core/control_io.py
- trestle/core/markdown/markdown_processor.py
- adjusts logging for consistency and adds critical logs for debugging (knowing which file created the error).
> fix: Ensure trackback logging occurs only on debug level.

- docs/tutorials/task.cis-to-component-definition/demo-cis-to-component-definition.config
- docs/tutorials/task.cis-to-component-definition/enabled_rules.json
- docs/tutorials/task.cis-to-component-definition/selected_rules.json
- docs/tutorials/task.cis-to-component-definition/transformation.md
- docs/tutorials/task.tanuim-to-oscal/transformation.md
- trestle/core/commands/author/headers.py
- trestle/tasks/cis_to_component_definition.py
Tutorial on use of task cis-to-component-definition.
```json
{
"example": "typed block"
}
```
> feat: tutorial for task cis-to-component-definition

- .github/PULL_REQUEST_TEMPLATE.md
> fix: Current support for multiple PR templates is insufficient in github.

- trestle/core/commands/author/ssp.py
quick fix of bad indent in loop
- Check sonar
> fix: tmp req init

- tests/data/json/minimal_catalog_with_groups.json
- tests/test_utils.py
- tests/trestle/core/commands/merge_test.py
- trestle/core/models/actions.py
Remove empty folders once `merge` is done.
- Check sonar
Closes #723
> fix: Remove empty folders after merge

- tests/data/markdown/valid_levels_no_text.md
- tests/data/markdown/valid_levels_no_text_increased_level.md
- tests/data/markdown/valid_no_headers.md
- tests/data/markdown/valid_no_lvl1_headers.md
- tests/trestle/core/markdown/markdown_node_test.py
- trestle/core/markdown/markdown_node.py
Added a functionality to modify the headers inside of the `MarkdownNode` by the given value. Also added a function to get the level of the node header.
- Check sonar
Closes #903
> feat: Add ability to modify headers in the tree

- .pre-commit-config.yaml
- docs/api_reference/trestle.core.commands.cmd_utils.md
- docs/api_reference/trestle.core.commands.common.cmd_utils.md
- docs/api_reference/trestle.core.commands.common.return_codes.md
- mkdocs.yml
- tests/data/json/test_profile_a.json
- tests/trestle/core/commands/author/ssp_test.py
- tests/trestle/core/control_io_test.py
- trestle/core/catalog_interface.py
- trestle/core/commands/author/ssp.py
- trestle/core/const.py
- trestle/core/control_io.py
- trestle/core/profile_resolver.py
Roles are now generated in the ssp metadata
New function to query params and param values in controls
- Check sonar
> feat: roles in metadata

- tests/data/tasks/cis-to-catalog/input-bogus/cis.profile
- tests/data/tasks/cis-to-catalog/input/cis.profile
- tests/data/tasks/cis-to-catalog/test-cis-to-catalog.config
- tests/trestle/tasks/cis_to_catalog_test.py
- trestle/tasks/cis_to_catalog.py
Add new trestle task cis-to-catalog that takes input file(s) cis.profile, cis-node.profile (from ComplianceAsCode) and transforms into OSCAL output file catalog.json.
- Check sonar
> feat: task cis-to-catalog

- docs/api_reference/trestle.tasks.cis_to_catalog.md
- docs/tutorials/task.cis-to-catalog/demo-cis-to-catalog.config
- docs/tutorials/task.cis-to-catalog/transformation.md
- docs/tutorials/task.cis-to-component-definition/transformation.md
- mkdocs.yml
New tutorial on creating OSCAL catalog from ocp4 CIS benchmarks using trestle task.
- Check sonar
> feat: tutorial cis-to-catalog

- trestle/core/markdown/md_writer.py
- trestle/core/ssp_io.py
> chore: Small fixes

- trestle/core/catalog_interface.py
> fix: catalog_interface attribute error

- trestle/core/catalog_interface.py
- trestle/core/markdown/markdown_api.py
- trestle/core/profile_resolver.py
Simple change to make get_group_info consistent with the cidd script
Also specify utf-8 when reading markdown.
> fix: cidd issues

- docs/assets/sample_ssp.md.jinja
- docs/trestle_author_jinja.md
- mkdocs.yml
- tests/data/jinja_markdown_include/MDSection_include_top_level_adjusted.jinja.md
- tests/data/jinja_markdown_include/env_include_adjusted.jinja.md
- trestle/core/jinja.py
> chore: documentation for the jinja command.

- trestle/core/jinja.py
> fix: add trailing newlines to md front_matter content

- docs/tutorials/ssp_profile_catalog_authoring/ssp_profile_catalog_authoring.md
- tests/data/yaml/header_with_metadata.yaml
- tests/trestle/core/commands/author/ssp_test.py
- tests/trestle/core/control_io_test.py
- trestle/cli.py
- trestle/core/commands/author/ssp.py
- trestle/core/commands/transform_oscal.py
- trestle/core/control_io.py
- trestle/resources/templates/FedRAMP_control_header_template.yaml
Reworked how headers are merged
Removed transform cmd from cli
initial update of docs
> fix: merge dicts

- .pre-commit-config.yaml
- docs/tutorials/ssp_profile_catalog_authoring/ssp_profile_catalog_authoring.md
- tests/test_utils.py
- tests/trestle/core/commands/author/ssp_test.py
- tests/trestle/core/commands/import__test.py
- tests/trestle/core/commands/replicate_test.py
- tests/trestle/core/commands/transform_oscal_test.py
Signed-off-by: Frank Suits <frankst@au1.ibm.com>
Converted all verbose assignments from boolean to integer
Added doc link to the ssp demo from the ssp tutorial
closes #984
> fix: change verbose assignments from boolean to integer

- README.md
Made several small improvements to `README.md`:
- Add `pip install` installation command line
- Small grammar improvements
> fix: README documentation improvements

- docs/tutorials/ssp_profile_catalog_authoring/ssp_profile_catalog_authoring.md
- tests/data/author/controls/control_with_bad_system_comp.md
- tests/data/author/controls/control_with_components.md
- tests/data/author/controls/control_with_components_and_param_template.md
- tests/data/author/controls/control_with_components_and_params.md
- tests/data/author/controls/control_with_double_comp.md
- tests/data/json/profile_missing_position.json
- tests/data/json/profile_with_alter_props.json
- tests/data/json/profile_with_incorrect_alter.json
- tests/data/json/simple_test_profile.json
- tests/data/json/test_profile_a.json
- tests/data/json/test_profile_d.json
- tests/trestle/core/commands/author/catalog_test.py
- tests/trestle/core/commands/author/profile_test.py
- tests/trestle/core/control_io_test.py
- tests/trestle/core/profile_resolver_test.py
Minor typo in tests and docs, from docs [tutorial about generated SSP authoring](https://ibm.github.io/compliance-trestle/tutorials/ssp_profile_catalog_authoring/ssp_profile_catalog_authoring/).
> fix: personell->personnel.

- tests/trestle/tasks/xlsx_to_component_definition_test.py
- trestle/tasks/xlsx_to_oscal_component_definition.py
Fix 2 bugs in task xlsx-to-oscal-component-definition.
Fixes issue #1016 
> fix: 2 bugs xlsx-to-oscal-component-definition

- trestle/core/resolver/_import.py
- Hot fix (emergency fix and release)
- Bug fix (non-breaking change which fixes an issue)
- Documentation (change which affects the documentation site)
- Breaking change (fix or feature that would cause existing functionality to change)
- Release (`develop` -> `main`)
This will resolve the issue reported in IBM/compliance-trestle#1019.
closes #1019 
closes #832 
closes #759
> feat: Resolve UUID Imports During Profile Resolution, Not Only Explicit Imports

- tests/test_utils.py
- tests/trestle/core/commands/author/catalog_test.py
- tests/trestle/core/commands/author/profile_test.py
- tests/trestle/core/commands/author/ssp_test.py
- tests/trestle/core/commands/transform_oscal_test.py
- tests/trestle/core/control_io_test.py
- tests/trestle/core/ssp_io_test.py
- trestle/common/const.py
- trestle/core/catalog_interface.py
- trestle/core/commands/author/catalog.py
- trestle/core/commands/author/profile.py
- trestle/core/commands/author/ssp.py
- trestle/core/commands/transform_oscal.py
- trestle/core/control_io.py
- trestle/core/resolver/modify.py
Allow all assemble commands to assemble into an optional json model
make author commands more consistent in params
provide required-sections option for profile-assemble
allow specification of section names in the yaml header
closes #1029
closes #1022
closes #1010 
> fix: consistent author commands and support for required-sections

- docs/api_reference/trestle.tasks.xlsx_to_oscal_cd.md
- docs/api_reference/trestle.tasks.xlsx_to_oscal_component_definition.md
- docs/cli.md
- mkdocs.yml
- scripts/oscal_normalize.py
- tests/data/tasks/xlsx/test-xlsx-to-oscal-cd.config
- tests/trestle/tasks/xlsx_to_oscal_cd_test.py
- trestle/tasks/xlsx_to_oscal_cd.py
- trestle/tasks/xlsx_to_oscal_component_definition.py
The spread sheet column heading matching was too lax. Two columns might be flagged as duplicates when in fact they had similar but not identical names.
> fix: Improve column heading matching.

- pyproject.toml
- setup.cfg
- tests/trestle/core/commands/init_test.py
- tests/trestle/core/commands/remove_test.py
- trestle/cli.py
- trestle/core/resolver/__init__.py
- trestle/resources/config.ini
> fix: Fix Jinja dependency version

- README.md
- docs/index.md
- setup.cfg
Updating docs to 1.0.0 and version to stable
> feat: Update docs to 100

- trestle/tasks/xlsx_helper.py
* Improved filtering column matching.
* Fix lint.
Co-authored-by: Frank Suits <47203786+fsuits@users.noreply.github.com>
small fix in develop merged to rc
> fix: Improved filtering column matching. (#1082)

- .pre-commit-config.yaml
- tests/data/tasks/xlsx/output/component-definition.json
- trestle/tasks/xlsx_helper.py
- trestle/tasks/xlsx_to_oscal_cd.py
fix to xlsx oscal bug lists of lists of setparams
> fix: xformer lists

- .pre-commit-config.yaml
- README.md
- docs/index.md
- docs/tutorials/task.ocp4-cis-profile-to-oscal-catalog/transformation.md
- docs/tutorials/task.ocp4-cis-profile-to-oscal-cd/transformation.md
- setup.cfg
- tests/data/jinja/profile_to_docs.md.jinja
- tests/data/jinja/profile_to_docs_invalid.md.jinja
- tests/data/tasks/xlsx/output/component-definition.json
- tests/trestle/core/commands/author/jinja_cmd_test.py
- tests/trestle/tasks/xlsx_to_oscal_cd_test.py
- trestle/core/control_io.py
- trestle/tasks/xlsx_helper.py
- trestle/tasks/xlsx_to_oscal_cd.py
Cherry picked multiple previously approved bug fixes/improvements from the `fix/hotfixes` branch.
Changes include:
- Better cloud-docs generation
- Docs improvements
- Bug fix for the transformers
> feat: Add multiple fixes for Trestle OSCAL 1.0.0 version

- docs/cli.md
Small fixes to cli.md for -name and some details about xslx task conversion
> docs: small fixes to cli.md

- README.md
- docs/index.md
Update readme and index md files
> docs: update readme and index md files

- README.md
- docs/index.md
fix bump version refs to 1.0.x
> fix: bump readme refs to 1.0.x

- README.md
- docs/index.md
> chore: Trestle Stable Release OSCAL 1.0.2

- trestle/core/control_io.py
Add ability to remove group title from docs
Closes #1108
> fix: Add ability to remove group title

- tests/data/json/simple_test_profile_no_params.json
- tests/trestle/core/profile_resolver_test.py
- trestle/core/resolver/modify.py
Prevent moustaches in resolved profile catalog because they cause jinja errors.
> fix: prevent moustaches in resolved profile catalog

- .pre-commit-config.yaml
- docs/index.md
- docs/maintainers.md
- [X ] Documentation (change which affects the documentation site)
> fix: updated documentation

- trestle/core/control_io.py
- trestle/core/markdown/markdown_node.py
Fixed problem with imp reqs being dropped if control has no parts in statement.
> fix: controls with no parts end up dropping imp_req prose

- .pre-commit-config.yaml
- tests/trestle/core/control_io_test.py
Resolved issue in pre-commit settings
> fix: resolve pre-commit issue

- .pre-commit-config.yaml
- tests/trestle/tasks/ocp4_cis_profile_to_oscal_cd_test.py
- tests/trestle/tasks/oscal_profile_to_osco_profile_test.py
- tests/trestle/tasks/osco_result_to_oscal_ar_test.py
- tests/trestle/tasks/xlsx_to_oscal_cd_test.py
- tests/trestle/tasks/xlsx_to_oscal_profile_test.py
Remove extraneous parens in test cases.
Closes #1101 
> fix: remove extraneous parens in unit tests.

- .pre-commit-config.yaml
- docs/api_reference/trestle.core.docs_control_writer.md
- mkdocs.yml
- tests/data/jinja/profile_to_docs_with_group_title.md.jinja
- tests/data/json/test_profile_a.json
- tests/trestle/core/commands/author/jinja_cmd_test.py
- trestle/common/const.py
- trestle/core/catalog_interface.py
- trestle/core/commands/author/jinja.py
- trestle/core/control_writer.py
- trestle/core/docs_control_writer.py
- trestle/core/ssp_io.py
Addressed various changes to the docs markdown, in particular:
- Added tag after each section
- Separated control writer into markdown for editing and docs markdown
- Parameters in the table can be overridden by "display-name"
- Removed capitalization of titles.
Closes #1157
> feat: Add various docs md improvements

- .pre-commit-config.yaml
- trestle/common/file_utils.py
> fix: utf8 issue

- tests/data/json/simple_test_profile.json
- tests/trestle/core/commands/author/profile_test.py
- trestle/common/const.py
- trestle/common/model_utils.py
- trestle/core/catalog_interface.py
- trestle/core/commands/author/profile.py
- trestle/core/control_interface.py
- trestle/core/control_reader.py
- trestle/core/resolver/modify.py
Handle display name as special property
namespace handling is only initially sketched in and will be filled in later.
partial #1161 
> feat: handle display name as property and initial handling of namespace option

- tests/trestle/core/commands/author/profile_test.py
- tests/trestle/core/control_io_test.py
- trestle/core/catalog_interface.py
- trestle/core/commands/author/profile.py
- trestle/core/control_reader.py
- trestle/core/control_writer.py
- trestle/core/markdown/md_writer.py
Fixed duplication of header content on re-generate
Fixed improper location of prose associated with statement parts
Fixed clean labeling of sections
> fix: duplicate headers and statement parts added in wrong place

- docs/trestle_author_jinja.md
- tests/data/jinja/profile_to_docs.md.jinja
- tests/data/jinja/profile_to_docs_invalid.md.jinja
- tests/data/jinja/profile_to_docs_only_some_sections.md.jinja
- tests/data/jinja/profile_to_docs_with_group_title.md.jinja
- tests/trestle/core/commands/author/jinja_cmd_test.py
- trestle/common/const.py
- trestle/core/docs_control_writer.py
- trestle/core/markdown/md_writer.py
Fixes various formatting issues with markdown docs
Partial #1164
> fix: Fix various issues in markdown docs

- tests/data/markdown/valid_complex_md.md
- tests/trestle/core/markdown/markdown_node_test.py
- tests/trestle/core/utils_test.py
- tests/trestle/utils/md_writer_test.py
- trestle/common/list_utils.py
- trestle/common/str_utils.py
- trestle/core/markdown/markdown_node.py
- trestle/core/markdown/markdown_processor.py
- trestle/core/markdown/md_writer.py
New functions to cull header nodes from a markdown header tree and write it out as md file.
> feat: allow culling headers from an existing md file

- tests/trestle/core/commands/author/component_test.py
- tests/trestle/core/commands/author/ssp_test.py
- trestle/core/commands/author/ssp.py
- trestle/core/control_reader.py
- trestle/core/control_writer.py
ssp-assemble was not capturing prose for control level imp_req prose
> fix: ssp-assemble was not capturing prose properly for control level imp req responses

- tests/trestle/tasks/csv_to_oscal_cd_test.py
- trestle/tasks/csv_to_oscal_cd.py
Closes Issue #1141.
Fixes problems identified in Issue #1141.
> fix: component definition issues

- tests/data/json/comp_def.json
- tests/data/json/simple_catalog_no_parts.json
- tests/test_utils.py
- tests/trestle/core/commands/author/catalog_test.py
- tests/trestle/core/commands/author/component_test.py
- tests/trestle/core/commands/author/profile_test.py
- tests/trestle/core/commands/author/ssp_test.py
- tests/trestle/core/control_io_test.py
- tests/trestle/core/ssp_io_test.py
- trestle/common/const.py
- trestle/common/model_utils.py
- trestle/core/catalog_interface.py
- trestle/core/commands/author/catalog.py
- trestle/core/commands/author/component.py
- trestle/core/commands/author/profile.py
- trestle/core/commands/author/ssp.py
- trestle/core/control_context.py
- trestle/core/control_interface.py
- trestle/core/control_reader.py
- trestle/core/control_writer.py
- trestle/core/markdown/markdown_node.py
Expanded test coverage for component and profile
Expanded yaml header content for rules and parameter values
Made parameter behavior in yaml headers more consistent
closes #1203 
> chore: expand test coverage and make markdown more consistent

- trestle/tasks/csv_to_oscal_cd.py
- [x My PR meets testing requirements.
- [x All new and existing tests passed.
> fix: trestle task csv-to-oscal-cd produces extraneous statements

- trestle/core/catalog_interface.py
Empty dirs were created during comp. gen.  Now they are created on demand for each control.
closes #1224 
> fix: empty dirs were created during comp-gen

- tests/trestle/core/commands/author/catalog_test.py
- trestle/core/catalog_interface.py
Add function to find full path to control including paths to sub-controls and not just groups.
> feat: provide full path to controls in catalog including sub-controls

- tests/data/author/controls/control_with_bad_component.md
- tests/data/author/controls/control_with_components.md
- tests/data/author/controls/control_with_components_and_params.md
- tests/trestle/core/ssp_io_test.py
- trestle/common/const.py
- trestle/core/control_reader.py
- trestle/core/control_writer.py
- trestle/core/ssp_io.py
Change implementation prompt to add "for part"
closes #1226
> fix: change implementation prompt for part

- tests/data/author/0.0.1/test_3_md_hand_edited/decisions_000.md
- tests/data/author/0.0.1/test_3_md_hand_edited/decisions_001.md
- tests/data/author/0.0.1/test_3_md_hand_edited/decisions_002.md
- tests/data/author/0.0.1/test_3_md_hand_edited/template.md
- tests/trestle/core/commands/author/docs_test.py
- trestle/core/markdown/markdown_api.py
- trestle/core/markdown/markdown_node.py
- trestle/core/markdown/markdown_validator.py
Fix a small bug when validating governed documents with the `--governed-heading` flag.
Closes #1186
> fix: Fix a bug in governed section validation

- tests/trestle/core/commands/author/component_test.py
- trestle/common/model_utils.py
- trestle/core/commands/author/component.py
component-assemble allows creation of a new component via markdown, but this code path was not implemented properly.  It now creates a new component as needed.  This component does not have metadata, so it also has no last_modified.
closes #1293
> fix: adding new components via markdown caused error

- README.md
- docs/index.md
> fix: change python badge for addressing current python supported versions

- MAINTAINERS.md
> docs: update maintainers.md for missed contributors

- tests/data/json/comp_def_a.json
- tests/trestle/core/commands/author/ssp_test.py
- trestle/core/catalog/catalog_interface.py
Error in specific case where component had rule parameter defined at component level
> fix: ssp-generate error with components

- trestle/core/catalog/catalog_interface.py
> fix: BREAKING CHANGE

- tests/trestle/core/commands/version_test.py
Fixed version test string to track latest version automatically.
> fix: Version test

- .github/workflows/python-push.yml
IBM open-source policy was changed to not allow any unverified Github actions to be used. This is a hotfix PR introduces the change to manually create a merge of main to dev.
> fix: Comply with IBM Github action policy

- .github/workflows/python-push.yml
Trestle hotfix release for main branch workflow
> chore: Trestle hotfix release

- .gitignore
- tests/data/jinja/ssp_template_no_input_profile_ssp.md.jinja
- tests/trestle/core/commands/author/jinja_cmd_test.py
- trestle/core/commands/author/jinja.py
fix for: https://github.com/IBM/compliance-trestle/issues/1342
> fix: update author jinja command and add test

- tests/trestle/core/commands/author/catalog_test.py
- trestle/core/markdown/base_markdown_node.py
- trestle/core/markdown/control_markdown_node.py
- trestle/core/markdown/markdown_processor.py
Raise a exception if the duplicate parts are found in the control statement.
Closes #1307
> fix: Raise error if duplicate parts are found in the control statement

- tests/trestle/core/commands/author/catalog_test.py
- trestle/core/markdown/control_markdown_node.py
- trestle/tasks/cis_xlsx_to_oscal_catalog.py
- trestle/tasks/csv_to_oscal_cd.py
- trestle/tasks/ocp4_cis_profile_to_oscal_catalog.py
- trestle/tasks/ocp4_cis_profile_to_oscal_cd.py
- trestle/tasks/xlsx_helper.py
- trestle/tasks/xlsx_to_oscal_cd.py
- trestle/tasks/xlsx_to_oscal_profile.py
- trestle/transforms/implementations/osco.py
- trestle/transforms/implementations/tanium.py
Handle tab presence in the parts of the control statement. 
Closes #1349
> fix: Handle tabs in statement prose and parts

- README.md
> Update community calls meeting notice

- trestle/tasks/cis_xlsx_to_oscal_catalog.py
> fix typo in task help text

- README.md
- docs/cli.md
Update webex link for the community call
> docs: update community call webex link

- README.md
> fix: update readme with webex details

- tests/trestle/core/commands/author/command_test.py
- tests/trestle/core/commands/href_test.py
- tests/trestle/core/commands/remove_test.py
Some tests failing on linux. Fixes #1386 
> fix: some tests failing on linux

- tests/data/jinja/profile_to_docs_no_part_prose.md.jinja
- tests/data/json/comp_prof_part_none.json
- tests/trestle/core/commands/author/jinja_cmd_test.py
- trestle/core/docs_control_writer.py
> fix: use empty string if prose in part is None while writing to markdown

- MAINTAINERS.md
- tests/data/jinja/profile_to_docs_no_part_prose.md.jinja
- tests/data/json/comp_prof_part_none.json
- tests/trestle/core/commands/author/catalog_test.py
- tests/trestle/core/commands/author/jinja_cmd_test.py
- trestle/core/docs_control_writer.py
- trestle/core/markdown/control_markdown_node.py
> fix: log warning for duplicate part ids when writing markdown from json

- docs/api_reference/trestle.tasks.oscal_catalog_to_csv.md
- mkdocs.yml
- tests/data/tasks/oscal-catalog-to-csv/test-oscal-catalog-to-csv-rev-5-by-control.config
- tests/data/tasks/oscal-catalog-to-csv/test-oscal-catalog-to-csv-rev-5-by-statement.config
- tests/trestle/tasks/oscal_catalog_to_csv_test.py
- trestle/tasks/cis_xlsx_to_oscal_catalog.py
- trestle/tasks/oscal_catalog_to_csv.py
> feat: oscal-catalog-to-csv

- .github/workflows/python-test.yml
> fix: python 3.7.17 issue

- README.md
> fix: change the community call to use bluejeans events

- tests/trestle/core/commands/author/profile_test.py
- trestle/common/const.py
- trestle/core/control_writer.py
> fix: assessment objectives formatting in markdown is not correct

- trestle/transforms/implementations/xccdf.py
> fix: xccdf parameter type

- setup.cfg
> fix: upgrade urllib version to fix vulnerability

- README.md
> fix: link main readme to agile authoring setup repo

- setup.cfg
> fix: correct critical vulnerability

- trestle/transforms/implementations/xccdf.py
> fix: sonar

- setup.cfg
> fix: trestle direct dependency on requests pkg

- tests/trestle/core/commands/author/profile_test.py
- trestle/core/catalog/catalog_reader.py
> fix: correct empty values going in assembled profile

- setup.cfg
> fix: correct security vulnerability

- setup.cfg
> fix: correct vulnerability

- README.md
> fix: zoom link

- release-1.1.2-schemas-fixup/oscal_assessment-plan_schema.json
- release-1.1.2-schemas-fixup/oscal_assessment-results_schema.json
- release-1.1.2-schemas-fixup/oscal_catalog_schema.json
- release-1.1.2-schemas-fixup/oscal_component_schema.json
- release-1.1.2-schemas-fixup/oscal_poam_schema.json
- release-1.1.2-schemas-fixup/oscal_profile_schema.json
- release-1.1.2-schemas-fixup/oscal_ssp_schema.json
- scripts/oscal_normalize.py
- scripts/schema_preprocess.py
- tests/trestle/core/commands/author/prof_test.py
- tests/trestle/core/profile_resolver_test.py
- tests/trestle/core/valid_values_test.py
- trestle/common/const.py
- trestle/core/control_reader.py
- trestle/core/resolver/merge.py
- trestle/core/resolver/modify.py
- trestle/oscal/common.py
- trestle/oscal/profile.py
- trestle/oscal/ssp.py
> fix: handle allOf construct

- .github/workflows/python-push.yml
> remove extraneous workflow lines of code

- README.md
> fix: remove obsolete text, fix broken links, fix spelling

- README.md
BREAKING CHANGE: for new release
> fix: updated README.md - breaking change

- trestle/core/catalog/catalog_interface.py
- trestle/core/catalog/catalog_merger.py
> fix: correct sonar quality checks

- tests/trestle/tasks/csv_to_oscal_cd_test.py
- trestle/tasks/csv_to_oscal_cd.py
Resolved #1461.
Converted all words in the heading to title cases when undecorating the heading. 
> feat: modify task csv_to_oscal_cd to allow any case for heading in csv file

- tests/trestle/tasks/csv_to_oscal_cd_test.py
- trestle/tasks/csv_to_oscal_cd.py
> fix: correct the argument for get_rule_key in csv_to_oscal_cd.py

- scripts/oscal_normalize.py
- tests/data/validate/component-definitions/x1/component-definition.json
- tests/data/validate/component-definitions/x2/component-definition.json
- tests/data/validate/component-definitions/x3/component-definition.json
- tests/trestle/core/commands/validate_test.py
- trestle/oscal/common.py
> fix: handle NonNegativeIntegerDatatype and PositiveIntegerDatatype in gen_oscal

- README.md
Removes communication details from README.md. Communication information is now centralized to
the community repo.
Closed #1587 
> docs: updates README.md communication details

- tests/trestle/tasks/csv_to_oscal_cd_test.py
- trestle/tasks/csv_to_oscal_cd.py
Resolved #1542
Note that I used `_execute()` instead of its wrapper `execute()` when testing because `execute()` would handle the exception and return `TaskOutcome('failure')`, preventing us to test the raised exception.
> refactor: update the error message when set parameters have invalid values

- setup.cfg
- tests/trestle/misc/_inventory.py
- tests/trestle/misc/mypy.cfg
- tests/trestle/misc/mypy_test.py
> fix: use pydantic.v1 plugin for mypy

- setup.cfg
> fix: correct vulnerabilities

- docs/demonstrations-content.md
1. The demo repo was recently updated. The trestle documentation webpage should also be updated.
> refactor: update trestle documentation webpage's Demo section to be in sync with the demo repo

- .github/workflows/codeql-analysis.yml
> fix: ensure codeql still runs on main

- docs/mkdocs_code_of_conduct.md
> docs: re-phrasing code of conduct reference

- .github/workflows/python-push.yml
- .github/workflows/python-test.yml
- version.json
- **ci: updates CI to read Python vars from a config**
- **fix: adds a checkout step to set version**
- **fix: updates inconsistent output setting**
- **fix: removes fromJson in workflow**
- **fix: updates the way outputs are referenced in CI**
- **fix: adds back fromJson**
Closes: #1627 
> fix: allow forks to correctly run the pipelines

- ROADMAP.md
Adds `ROADMAP.md`
Closes #1480 
Closes #1622 
> docs: adds ROADMAP.md with high level roadmap description

- CONTRIBUTING.md
- README.md
- docs/mkdocs_code_of_conduct.md
> docs: updates README to align with CNCF project template

- README.md
> fix: correct logo redirection for PyPi page

- .github/dependabot.yml
Add dependabot configuration which we can use to our GitHub Actions  and pip dependencies.
Closes #1541 
> feat: adds dependabot configuration for continuous updates

- .github/dependabot.yml
Fixes invalid dependabot configuration
> fix: updates invalid dependabot configuration

- trestle/tasks/cis_xlsx_to_oscal_catalog.py
> fix: cis benchmarks to catalog task, which mistakenly does not see all columns

- README.md
- docs/index.md
Closes: #1685
Signed-off-by: Chris Butler <chris.butler@redhat.com>
> fix(docs): correct build status icon is displayed in docs

- .github/workflows/stale.yml
- ROADMAP.md
Adds initial information on triaging process and automated for handling stale issues
Closed #1643 
> chore: adds initial triaging process and stale issue handling

- CONTRIBUTING.md
> fix: add testing policy to contributing.md

- .pre-commit-config.yaml
- scripts/flatten_schema.py
- scripts/oscal_normalize.py
- scripts/schema_integrity.py
- tests/trestle/core/base_model_test.py
- tests/trestle/core/generator_test.py
- tests/trestle/core/remote/cache_test.py
- trestle/core/markdown/markdown_validator.py
- trestle/tasks/cis_xlsx_to_oscal_catalog.py
- trestle/tasks/csv_to_oscal_cd.py
- trestle/tasks/ocp4_cis_profile_to_oscal_catalog.py
- trestle/tasks/ocp4_cis_profile_to_oscal_cd.py
- trestle/tasks/oscal_catalog_to_csv.py
- trestle/tasks/xlsx_to_oscal_cd.py
- trestle/tasks/xlsx_to_oscal_profile.py
- trestle/transforms/transformer_factory.py
This cleans up some deprecation alerts before the become issues. I also had to update flake8 due to incompatibilities which were occuring.
> fix(refactor): clean up timezone deprecations

- tests/data/csv/rule-name-overlap.csv
- tests/data/tasks/csv-to-oscal-cd/test-csv-to-oscal-cd-rule-name-overlap.config
- tests/trestle/tasks/csv_to_oscal_cd_test.py
- trestle/tasks/csv_to_oscal_cd.py
> fix: support rule overlap for checks and target components

- trestle/core/control_interface.py
Uses the aggregate parameter label if no sub-parameters have values specified.
- Fixes #1706
> fix(profile-resolve): handle unspecified aggregate parameters

- docs/demos.md
Required to fix a broken build process
Signed-off-by: Chris Butler <chris.butler@redhat.com>
> chore: fix broken URL

- mkdocs.yml
- setup.cfg
This adds build minimisation to the html website. 
Closes: #1702
> chore(docs): minimize website html during build

- .github/workflows/docs-update.yml
> fix: needs are explicit

- setup.cfg
Updates setup.cfg to change author and email. PyPi picks these details from this file.
> fix: update setup.cfg to change author and email

- .github/workflows/docs-update.yml
Ensures changes are pushed to the gh-pages branch
> fix: adds --push to mike depoly

- .github/workflows/docs-update.yml
> fix: set user id for doco pipeline

- mkdocs.yml
Now that mike is actually working this will trigger the versions to be displayed
> fix: activate mike

- CONTRIBUTING.md
- README.md
- docs/tutorials/Transformers_and_Tasks/OCP4_CIS_profile_to_oscal_cd.md
- docs/tutorials/Transformers_and_Tasks/csv_to_oscal_cd.md
- docs/tutorials/Trestle_authoring/ssp_profile_catalog_authoring.md
- docs/tutorials/Trestle_authoring/trestle_author.md
- tests/trestle/core/commands/author/ssp_test.py
- trestle/core/catalog/catalog_reader.py
- trestle/core/control_interface.py
Add tests and logic to ensure existing added properties and replaced and not duplicated on each assemble.
Closes #1798 
> fix: updates ssp add-props to replace existing properties

- trestle/tasks/cis_xlsx_to_oscal_catalog.py
> fix: add deprecation warning

- .gitmodules
- Makefile
- docs/contributing/website.md
- scripts/gen_oscal.py
- scripts/oscal_normalize.py
> fix: remove submodule nist-source

- mkdocs.yml
Updates mkdocs `htlmproofer` config to ignore anchors in relative paths.
> fix: updates mkdocs.yml to ignore anchors on relative paths

- SECURITY-INSIGHTS.yml
- mkdocs.yml
- setup.cfg
- tests/test_utils.py
- tests/trestle/core/ssp_io_test.py
- trestle/core/ssp_io.py
> chore: trestle patch release

- tests/data/tasks/xccdf/output-oscap-arf-results/results_arf.oscal.json
- tests/data/tasks/xccdf/output-oscap-results/results.oscal.json
- trestle/transforms/implementations/xccdf.py
> fix: property is missing required field

- trestle/core/catalog/catalog_interface.py
- trestle/tasks/csv_to_oscal_cd.py
- trestle/tasks/synthesize_oscal_cd.py
> Bridge/synthesize cd.fix imp req

- .github/dependabot.yml
Update the dependabot commit prefix
Fixes #1788
> fix: prefix dependabot messages with fix

- CONTRIBUTING.md
- trestle/common/type_utils.py
- trestle/core/base_model.py
Updates  a broken link and comments for a new version of mypy.
Should unblock #1885 
> ci: updates for failing CI jobs

- docs/tutorials/Transformers_and_Tasks/transformer_construction.md
- docs/tutorials/cli.md
Fixes formatting in Markdown files causing CI failures.
> docs: fixes markdown formatting in docs

- .github/dependabot.yml
- .github/workflows/docs-update.yml
- .github/workflows/python-push.yml
- .github/workflows/python-test.yml
- CONTRIBUTING.md
- Makefile
- docs/contributing/website.md
- docs/tutorials/Transformers_and_Tasks/transformer_construction.md
- docs/tutorials/cli.md
- pyproject.toml
- trestle/common/type_utils.py
- trestle/core/base_model.py
> chore: Trestle release 3.9.1

- mkdocs.yml
> fix: 2 URLs failing htmlproofer during make docs-validate

- .github/workflows/python-push.yml
- CHANGELOG.md
- pyproject.toml
> fix: changelog
