oscal-compass/compliance-trestle

docs/trestle-spec.md, test/data/split_merge/.trestle/config.ini, test/data/split_merge/README.md, test/data/split_merge/step3-split_metadata_array_additionalproperties_elements/catalogs/mycatalog/next_step.sh
---
- fix example of target-definition models replacing components by targets and control-implementations by target-control-implementations.
- fix split command with -e groups[].controls[] and add example for .trestle/config.ini
- Add trestle replicate (formerly known as trestle duplicate) to the list of trestle …
=> docs: fix target-definition examples in trestle specifications

.github/dco.yml
This change ensures that DCObot will not break our ability to commit as members of the organisation. DCOBot configuration is gated by the IBM github organisation. If we cannot use DCO bot we may need to resort to simpler methods (tickbox in PR template).
=> Ensuring DCO bot does not limit core team access.

.pre-commit-config.yaml, CHANGELOG.md, setup.cfg
Allows semantic release to correctly publish a changelog for trestle.  Should complete #103
=> chore: Allow changelog to be automatically populated by semantic-release

.github/workflows/precommit-update.yml, .github/workflows/python-push.yml, .github/workflows/python-test.yml, Makefile
This adds functionality to ensure that pre-commit does the following:
1. Does not cause issues on releases
1. When pre-commit is updated a PR will be automagically generated if this occurs - keeping us up to date.
=> chore: Separating pre-commit actions and creating an automatic update

trestle/core/commands/remove.py
Previously, supplying **trestle remove** with a file argument using an unsupported extension would raise a SystemExit after *parent_mode.oscal_read()* with messy complaints because it was not handled properly in *RemoveCmd*. It was previously ready only for a *FileNotFoundError*. The change …
=> Handling bad file extension in arg to trestle remove with clean error message

tests/test_utils.py, tests/trestle/conftest.py, tests/trestle/core/remote/cache_test.py, trestle/core/remote/cache.py, trestle/utils/fs.py, trestle/utils/trash.py
Working with Chris' initial work with caching/remote resources, I've extended the fetcher code with at least valid fetchers that are selected correctly on the basis of the uri given. Working unit testing for that.
Note this is to merge into *feature/remote*, **not** into *develop*.
=> New caching code and unit tests, and bringing remote work up to sync with develop today

docs/caching_spec.md
This fixes typos and tabular format in the caching specs, and disallows unencrypted HTTP for fetching.
=> Docs/caching spec typos and format fixed, updated to disallow unencrypted HTTP

.pre-commit-config.yaml, docs/caching_spec.md
Thought you might find the mdformat-gfm plugin useful. It changes Markdown spec from Commonmark to GFM, so tables, for instance, are formatted. No longer need to manually make whitespace align :smile:
=> Autoformat GFM tables with mdformat-gfm

tests/trestle/core/remote/cache_test.py, trestle/core/remote/cache.py
Just implemented *get_raw()* base class method. It will update the cache if not *self.in_cache()* or if *self._refresh*. It uses and returns content via *load_file()* in  *trestle.utils.fs*, which should mean it can handle other formats like yaml, and anything else, e.g., xml, if subsequently supported by that module.
Linting, formatting and testing only cover the change. I am not touching other parts of cache.py and its unit tests, e.g., github. 
- \[ \] I have …
=> get_raw() in base class implemented

tests/trestle/core/remote/cache_test.py, tests/trestle/core/settings_test.py, trestle/core/remote/cache.py, trestle/core/settings.py
get_oscal() simply users oscal_read() for the given model_type. Basic validation for:
* existence of the cache_file pointed to by the *self._uri* base (file) name inside *self._inst_cache_path*
* success of oscal_read()
Caveat 1: It is arguable whether it is desirable to have *_update_cache()* update *self._inst_cache_path* with the final cache file rather than just the containing directory. At this point, I am assuming the latter. If we go with the former, then this code will need to change.
Caveat 2: From the current commit 3dfe3b91c0 of `feature/remote`, I did not touch code except *get_oscal()*. However, I think make code-format updated *settings.py* and *settings_test.py*, as well as other parts of *cache.py* that I did not edit, such as the *HTTPSFetcher()* and the *GithubFetcher* …
=> get_oscal() implemented in base class, and tested

tests/trestle/core/remote/cache_test.py, tests/trestle/core/settings_test.py, trestle/core/remote/cache.py, trestle/core/settings.py
This completes unit tests for the sftp fetcher -- as far as I could take it a least. Three lines of exception handling are covered only with real SFTP sessions (via ssh-agent, so no passwords) but this test is not portable outside my workstation, so that is not include here. There is a separate issue for integration testing: #316.
Taken as a whole, trestle.core.remote.cache does not pass test and code format/lint due to other remote fetching code, which I did not touch, in the current version of `feature/remote`.
- \[ \] …
=> sftp fetcher testing completed, mostly

docs/cli.md
- \[x] My change requires a change to the documentation.
Update docs/cli.md documentation for trestle `task osco-to-oscal` configuration parameters comprising:
- input-dir: required - contains osco evidence .yaml files and optional oscal metadata .yaml file.
- output-dir: required - contains created OSCAL partial Assessment Results .json file.
- …
=> website documentation for trestle task osco-to-oscal

tests/data/tasks/osco/output/osco-pod-oscal-arp.json, tests/data/tasks/osco/output/osco-pod-oscal.json, tests/trestle/utils/osco_test.py, trestle/utils/osco.py
Provide additional OSCO utility to transform .yaml into OSCAL observations as json. Utility currently provides transformation to trestle objects only, which requires utility user to employ trestle objects perhaps unnecessarily.
- new `trestle.utils.osco.get_observations_json()` wraps …
=> Utility to transform OSCO yaml data into OSCAL observations json data.

tests/trestle/core/commands/import__test.py, trestle/core/commands/import_.py
An import will use a trestle validation to roll back if the latter rejects the imported content. There is some inefficiency in the way validation only works on in-project content, but that's all we have at present. The alternative is to write separate validation code prior to import. Additionally, validation only checks for uuid duplicates. Should other modes become available, trestle import should be modified to use them.
- \[ \] I have updated the documentation …
=> Validation to test for duplicates added to trestle import

tests/trestle/core/commands/assemble_test.py, trestle/core/commands/assemble.py
Assemble can now perform for all models of specified type.  Currently the Plan created is for each model assembled - rather than for the entire operation.  It can be done for the entire operation, but having it succeed as much as possible is perhaps better.
=> Added bulk operations for assemble

tests/trestle/core/commands/assemble_test.py, trestle/core/commands/assemble.py
This fix is relatively simple. The purpose is to improve the usability of assemble for use within a CI/CD pipeline. Specifically lack of a model is not a failure criteria. This allows for standardized models / scripts to be used rather …
=> Allow assemble to succeed when no model is found.

trestle/cli.py, trestle/core/commands/add.py, trestle/core/commands/assemble.py, trestle/core/commands/command_docs.py, trestle/core/commands/create.py, trestle/core/commands/import_.py, trestle/core/commands/init.py, trestle/core/commands/merge.py, trestle/core/commands/remove.py, trestle/core/commands/replicate.py, trestle/core/commands/split.py, trestle/core/commands/task.py, trestle/core/commands/validate.py
The ILCLI interface has a bit of a flaw from a documentation perspective: The 'Command' class docs are only used for sub-command hints on help.
This PR generalizes the use of docstrings for CLI documentantion to improve user experience. …
=> Improving documentation for commands in trestle CLI

setup.cfg, tests/trestle/core/commands/add_test.py, tests/trestle/core/commands/create_test.py, tests/trestle/core/commands/merge_test.py, tests/trestle/core/commands/remove_test.py, tests/trestle/core/commands/split_test.py, tests/trestle/utils/load_distributed_test.py
Signed-off-by: FrankSuits <frankst@au1.ibm.com>
Make sure rc in tests is checked whenever a command is run.
Also removed dependency on dictdiffer since tests were only checking for equality of dicts and not the specific differences between dicts.
=> issue #344 check rc in tests and remove dependency on dictdiffer

tests/trestle/core/base_model_test.py, trestle/core/base_model.py, trestle/core/markdown_validator.py
Added support for OscalBaseModel to produce serialised output suitable for machine to machine consumption.
Closes #453
=> feat:Improved serialisation support.

.github/workflows/conventional-pr.yml, .github/workflows/python-push.yml, .github/workflows/trestle-develop-automerge.yml, .github/workflows/trestle-main-automerge.yml
Original intent was to ensure that conventional commits blocked merges to ensure user would edit the commit.
=> fix: Correct semantic / conventional commit behaviour

.github/workflows/python-push.yml
The concurrency restrictions affect matrix builds in a really nasty way. I've removed the restriction (designed to accelerate the build process), however, left in critical components - where it ensures that the release process happens …
=> fix: Remove problematic concurrency restrictions in devops pipeline

.github/workflows/trestle-develop-automerge.yml
The refs coming to automerge are not as expected. Refactor to take into account this behaviour.
=> fix: Improve devops to stop squash merging to main

trestle/core/commands/split.py
- \[ \] All commits are signed-off.
Debug statement indicating start of split command was before logging level set - therefore the only way this debug statement is displayed is by editing cli.py to set the logging level, or editing utils/log.py to change the default level. Moving debug statement after logging level is set …
=> fix: move unreachable debug statement

tests/trestle/core/commands/author/ssp_test.py, trestle/core/commands/author/ssp.py
Improved handling of general prose for responses used in ssp-assemble.
closes #578 
Will need separate issue to determine exactly what is allowed in the text, but this change will extract all text between ###Part X and --- (horizontal rule) - after first removing any leading and trailing …
=> fix: ssp assemble prose, all extraction of general prose for responses

mkdocs.yml, tests/test_utils.py, tests/trestle/core/commands/author/ssp_test.py, tests/trestle/core/commands/cmd_utils_test.py, tests/trestle/core/commands/split_test.py, tests/trestle/utils/fs_test.py, trestle/core/commands/cmd_utils.py, trestle/core/commands/split.py, trestle/core/utils.py, trestle/utils/fs.py
can now split catalog.*
and also go deep with split catalog.metadata.roles.*
closes #423
=> fix: split catalog star, enable split of model with wildcard

tests/trestle/core/commands/author/ssp_test.py, trestle/core/commands/author/ssp.py
Signed-off-by: Frank Suits <frankst@au1.ibm.com>
Minor change needed due to OSCAL 1.0.0
section name was changed in new catalog file, and schema for section name also changed.
=> fix: ssp section generation failed due to changes due to 1.0.0

tests/data/tasks/xlsx/output/catalog.json, tests/data/tasks/xlsx/output/component-definition.json, tests/trestle/tasks/xlsx_to_component_definition_test.py, trestle/tasks/xlsx_to_oscal_component_definition.py
trestle version increases with each release, which affects the produced
output but not in any material way with respect to the unit tests at
hand.
fix is to employ local function to get_trestle version which nominally
returns the actual trestle version, but to mock said function in the
unit test.
=> fix: file compare issue in task xlsx-to-component-definition unit test

tests/trestle/core/generator_test.py, trestle/core/base_model.py, trestle/core/generators.py
Allows the generator to generate optional classes. Nice and safe in terms of what it can generate. More complex object can be generated by chaining this functionality together.
The idea would be to introduce this to `trestle add`.
closes: #599
=> feat: Adding capability to allowing generator to generate optional fields.

setup.cfg
- [] I have updated the documentation accordingly.
This fix is required as 0.25.0 due to some setup.cfg changes excludes trestle submodules (e.g. trestle.core). I've refactored the setup.cfg to include the necessary files only (which includes all python files under trestle/ as well as any data files under trestle/ (data files are non-python files such as py.typed).
Closes #749 
Opened long term solution to ensure this does not happen: #750 
- Clone / pull code
- cd compliance-trestle
- python setup.py bdist_wheel
- cd dist
- unzip compliance-trestle*.whl
- examine files within the expanded directories.
=> fix: Emergency fix for trestle packaging.

tests/data/json/profile_with_alter_props.json, tests/trestle/core/profile_resolver_test.py, trestle/core/profile_resolver.py
Allow Alter/Add to add prop by_id, where the id is a param_id in the control
Also changed all add.position to use the Enum form of profile.Position
closes #818
=> fix: all Alter/Add of prop by_id

trestle/core/control_io.py, trestle/core/profile_resolver.py
Changed TrestleError to warning.  Provide warning when doing profile generate.  Added strip() to captured prose.
=> fix: profile resolver issues with alter that has no adds

tests/trestle/core/commands/author/catalog_test.py, tests/trestle/core/commands/author/profile_test.py, tests/trestle/core/commands/author/ssp_test.py, tests/trestle/core/control_io_test.py, tests/trestle/utils/md_writer_test.py, trestle/core/catalog_interface.py, trestle/core/commands/author/catalog.py, trestle/core/commands/author/profile.py, trestle/core/commands/author/ssp.py, trestle/core/const.py, trestle/core/control_io.py, trestle/core/markdown/md_writer.py
- Adds an extra flag to ensure that the yaml header passed is non destructive
- This is required to cater to scenarios where a control is 'added' in a workflow.
- Also includes fixes to remove yaml reordering.
=> feat: Add yaml header to various trestle author docs in a safe manner.

tests/trestle/core/commands/assemble_test.py, tests/trestle/core/commands/author/command_test.py, tests/trestle/core/commands/author/docs_test.py, tests/trestle/core/commands/author/folders_test.py, tests/trestle/core/commands/replicate_test.py, tests/trestle/core/commands/task_test.py
This improves more unittest *patch* blocks (from the mock library) with *monkeypatch* instead, to avoid the indentations and subsequent asserts. Actually this one takes care of blocks missed in [this previous PR](https://github.com/IBM/compliance-trestle/pull/739), which addressed issue #673 (which was resolved back then).
=> refactor: use monkeypatch to replace more mock library patch blocks

tests/data/json/profile_bad_control.json, tests/trestle/core/commands/author/ssp_test.py, trestle/core/profile_resolver.py
Profile referencing control not in catalog caused exception with no error info.
Now catch the exception and provide details on the control and profile involved.
closes #892 
- Check sonar
=> fix: bad control causes uncaught exception in ssp-generate

tests/trestle/core/commands/author/ssp_test.py, trestle/core/catalog_interface.py, trestle/core/commands/author/ssp.py
- Changes the behaviour of spp-generate to default to using all sections.
- Check sonar
=> feat: Altering ssp-generate to add all sections by default

tests/trestle/core/commands/assemble_test.py, tests/trestle/core/commands/create_test.py, tests/trestle/core/commands/import__test.py, tests/trestle/core/commands/merge_test.py, tests/trestle/core/commands/remove_test.py, tests/trestle/core/commands/replicate_test.py, trestle/core/commands/add.py, trestle/core/commands/assemble.py, trestle/core/commands/create.py, trestle/core/commands/import_.py, trestle/core/commands/merge.py, trestle/core/commands/remove.py, trestle/core/commands/replicate.py, trestle/core/commands/split.py, trestle/core/models/plans.py, trestle/core/repository.py
Remove `simulate()` from the commands.
- Check sonar
Closes #906
=> chore: Remove simulate from Plan

mkdocs.yml
Closes: https://github.com/IBM/compliance-trestle/issues/529
Signed-off-by: Ryan Moats <rmoats@us.ibm.com>
Set edit_url field in mkdocs.yml to empty string to see if that removes the pencil icon (edit function) from rendered pages.
=> docs: clear edit_uri to remove edit pencil

Makefile, scripts/simplify_retain_ac.py, tests/conftest.py, tests/data/json/simplified_nist_catalog.json, tests/data/json/simplified_nist_profile.json, tests/test_utils.py, tests/trestle/core/commands/author/catalog_test.py, tests/trestle/core/commands/author/profile_test.py, tests/trestle/core/commands/author/ssp_test.py, tests/trestle/core/commands/cmd_utils_test.py, tests/trestle/core/commands/describe_test.py, tests/trestle/core/commands/href_test.py, tests/trestle/core/commands/import__test.py, tests/trestle/core/commands/split_test.py, tests/trestle/core/profile_resolver_test.py, tests/trestle/core/repository_test.py, tests/trestle/core/validator_helper_test.py
Created a new script, *simplify_retain_ac.py*, based on the previous *simplify_catalog.py* script, but this time preserving controls *ac-1* through *ac-5* as they are needed for certain tests whereas other lists, e.g., groups itself, other controls and their contents, can be pruned down as desired.
fsuits then added a rule for simplified-catalog to the Makefile to generate the catalog as needed over time.  All tests now use a simplified catalog and profile.
This closes #884.
=> feat: custom pruning for a smaller catalog but preserving controls ac-1 through -5

trestle/core/control_io.py
Updates the output for control headings to use the label, e.g. AC-2(1), rather than the control ID, e.g. ac-2.1, because the labels are commonly used to refer to controls in documents. 
The else clause allows for the case where controls do not have a label set (for example the IBM control catalog) - or does this highlight an issue elsewhere if controls do not have a label set?
Removed the group title from the titles, not necessary here.
=>  fix: update control title format for ssp output

trestle/core/catalog_interface.py
- Handles an error found when profile.modify was null
=> fix: Handle error when dealing with profiles with no modify object.

README.md
Signed-off-by: Doug Chivers <doug.chivers@uk.ibm.com>
Contributing link in readme.md lead to 404
=> fix: fix blind link in readme

.pre-commit-config.yaml
Signed-off-by: Doug Chivers <doug.chivers@uk.ibm.com>
Fixes https://github.com/IBM/compliance-trestle/issues/971 where `make code-format` fails due to missing toml dependency. This is caused by yapf not including toml in its dependencies, so it is not installed in the venv created by pre-commit.
=> fix: add toml as yapf pre-commit dependency

.pre-commit-config.yaml, docs/cli.md, docs/reference/third-party-result-schema-SCC.md, docs/tutorials/task.transformer-construction/transformer-construction.md
Signed-off-by: Doug Chivers <doug.chivers@uk.ibm.com>
- [] My PR meets testing requirements.
- [] All new and existing tests passed.
`make mdformat` would raise errors due to inability to format json, which could be misleading to users creating documentation (it appears there is a json formatting error, rather than the standard reformat due to a documentation change), and prevents mdformat reformatting the block. For example:
```
pre-commit run mdformat --all-files
mdformat.................................................................Failed
- hook id: mdformat
- files were modified by this hook
Warning: Failed formatting content of a json code block (line 429 before formatting)
Warning: Failed formatting content of a json code block (line 518 before formatting)
Warning: Failed …
```
=> fix: fix json blocks in md so mdformat doesnt raise cannot format warn

tests/data/author/controls/control_no_labels.md, tests/data/author/controls/control_some_labels.md, tests/trestle/core/commands/author/catalog_test.py, tests/trestle/core/control_io_test.py, trestle/core/catalog_interface.py, trestle/core/commands/author/catalog.py, trestle/core/commands/author/profile.py, trestle/core/const.py, trestle/core/control_io.py
Group titles weren't handled properly in several places and were lost when reading from markdown.  Now fixed.
Extra editable field was being created improperly with catalog generate
Profile generate wasn't creating parameter headers properly based on set-parameters flag
Profile assemble now has name as optional and otherwise defaults to the output profile name
Test files now use group titles better
closes #962 
closes #966 
closes #967 
closes #968
=> fix: several issues in profile assemble and catalog generate

docs/trestle_author_jinja.md, tests/trestle/core/commands/author/jinja_cmd_test.py, trestle/core/commands/author/jinja.py, trestle/core/control_io.py, trestle/core/profile_resolver.py
Added additional flag to `trestle author jinja -pf`. This flag allows users to add some text to the parameters or even wrap parameters with specified symbols. To cover all possible scenarios like adding text at the beginning or the end or wrapping the parameters, the decision was to reserve dot `.` to indicate the position of the parameter.
E.g. `trestle author ninja -pf *.*` will italicize all substituted parameters. Or `trestle author jinja -pf Prefix:.` will add `Prefix:` to the beginning of each parameter.
- Check sonar. If you are working for a fork a maintainer will reach …
=> feat: Add custom parameter wrapping to jinja

tests/trestle/core/commands/merge_test.py, trestle/core/commands/merge.py, trestle/core/commands/split.py, trestle/core/repository.py, trestle/utils/log.py
Simple way to add the ability to output trace messages when verbose > 1 - without messing with the logging itself.
If acceptable we can expand its usage.
If it needs to be changed, it should be easy to change all usages.
=> fix: allow trace logging with verbose level 2

tests/test_utils.py, tests/trestle/core/commands/init_test.py, tests/trestle/core/remote/cache_test.py, tests/trestle/utils/fs_test.py, trestle/core/commands/command_docs.py, trestle/core/commands/init.py, trestle/core/const.py, trestle/utils/fs.py
Added a consistency check for OSCAL directories. No other files than `json | xml | yaml` or `md` are allowed to be in the directories. Hidden files are deleted automatically.
Also fixed a small bug related to `.keep` files on Windows
Closes #678
=> feat: Validate OSCAL directories

tests/trestle/core/commands/author/catalog_test.py, trestle/core/catalog_interface.py
Fix allows jinja to query catalog_interface for controls in order sorted by sort-id
Needed by and hooked into the ssp-demo separately
=> fix: added methods in catalog interface to sort controls by sort-id

.pre-commit-config.yaml, tests/data/jinja/profile_to_docs.md.jinja, tests/data/jinja/profile_to_docs_invalid.md.jinja, tests/trestle/core/commands/author/jinja_cmd_test.py, trestle/core/control_io.py
Addressed the feedback for cloud-docs generation:
1. Title is now capitalized
2. Sections can be printed in the arbitrary order.
3. `group_title` now is mandatory
=> fix: Improve cloud-docs generation

README.md, docs/index.md, docs/tutorials/trestle_sample_workflow.md, scripts/simplify_retain_ac.py, tests/data/tasks/ocp4-cis-profile-to-oscal-cd/output/component-definition.json, tests/data/tasks/osco/output-1.3.5/ssg-ocp4-ds-cis-111.222.333.444-pod.oscal.json, tests/data/tasks/osco/output-compressed/ssg-rhel7-ds-cis-111.222.333.444-pod.oscal.json, tests/data/tasks/osco/output-configmaps/configmaps.oscal.json, tests/data/tasks/osco/output-fetcher/cluster_resource.oscal.json, tests/data/tasks/osco/output-xml-ocp4/ocp4-check-result.oscal.json, tests/data/tasks/osco/output-xml-rhel7/rhel7-check-result.oscal.json, tests/data/tasks/osco/output/ssg-ocp4-ds-cis-111.222.333.444-pod.oscal.json, tests/data/tasks/tanium/output/Tanium.oscal.2020.json, tests/data/tasks/tanium/output/Tanium.oscal.json, tests/data/tasks/xlsx/output-filtered/profile.json, tests/data/tasks/xlsx/output/component-definition.json, tests/data/tasks/xlsx/output/profile.json, trestle/core/generators.py, trestle/oscal/__init__.py, trestle/oscal/assessment_plan.py, trestle/oscal/assessment_results.py, trestle/oscal/catalog.py, trestle/oscal/common.py, trestle/oscal/component.py, trestle/oscal/poam.py, trestle/oscal/profile.py, trestle/oscal/ssp.py, trestle/transforms/implementations/osco.py, trestle/transforms/implementations/tanium.py
Now support OSCAL version 1.0.2
Regenerated oscal models and changed prop to props in assessment_results
Moved oscal REGEX to support both 1.0.0 and 1.0.2 on import
Files created will be version 1.0.2
BREAKING CHANGE
=> feat: updated to OSCAL 1.0.2 support

setup.cfg
Force back level version of cryptography so it doesn't warn about blowfish deprecation.
closes #1111 
=> fix: prevent blowfish warning due to new release of cryptography

tests/data/jinja/profile_to_docs_with_group_title.md.jinja, tests/trestle/core/commands/author/jinja_cmd_test.py, trestle/core/control_io.py
Add control id to the generated docs
=> fix: Add control id to the generated docs

docs/trestle_author.md, tests/trestle/core/commands/author/ssp_test.py, tests/trestle/core/ssp_io_test.py, trestle/core/commands/author/ssp.py, trestle/core/ssp_io.py
Added new ability to filter ssp by component
This filters from OSCAL/json to OSCAL/json using a mixture of profile and/or component names
closes #1040
=> feat: filter ssp by component

docs/trestle_author.md, tests/trestle/core/commands/author/ssp_test.py, trestle/core/commands/author/ssp.py, trestle/core/control_io.py
ssp-assemble now ignores case and space in component names
ssp-filter now blocks overwrite of output ssp if no changes relative to existing file.
=> fix: ssp-assemble now ignores case and space in comp names

scripts/have_files_changed.py, tests/trestle/core/commands/author/versioning/template_versioning_test.py, trestle/common/const.py, trestle/core/commands/author/common.py, trestle/core/commands/author/folders.py, trestle/core/commands/author/versioning/template_versioning.py
- Allowed subfolders to be inside of the template folders.
- Ignored PNG and any other files that are not drawio or markdown from validation
Closes #1105
=> fix: Allow subfolders in the template folders

scripts/oscal_normalize.py, trestle/oscal/assessment_plan.py, trestle/oscal/assessment_results.py, trestle/oscal/common.py, trestle/oscal/component.py, trestle/oscal/poam.py
The schemas used to create the oscal class files include classes that aren't referenced in the file.  This caused the final oscal files to include classes that were not needed, with SetParameter being the main problem.  Innocuous but undesirable - now fixed.
=> fix: remove unused classes from the generated oscal files

tests/trestle/core/commands/author/folders_test.py, trestle/core/commands/author/folders.py
Currently `author folders` will validate extra files in the task folder, which cause validation to fail in some cases. Those files should be skipped instead. This is a small fix to handle this edge case.
=> fix: Do not validate extra files when author folders

setup.cfg, trestle/core/commands/author/folders.py, trestle/core/markdown/markdown_validator.py
Improved logging for when validation of the headings fails for governed docs. Now it will notify the user which heading was expected.
Closes #1132
=> fix: Improve logging when validating headings in gov docs

tests/trestle/core/commands/author/catalog_test.py, trestle/common/model_utils.py, trestle/core/catalog_interface.py, trestle/core/commands/author/catalog.py, trestle/core/commands/author/profile.py
If you assemble a catalog from markdown and then assemble again, it overwrites when it shouldn't.  But on next assemble it does not overwrite.  This was caused by an empty params list in the assembled catalog that has now been removed.
closes #1136
=> fix: catalog-assemble was writing a new file when there were no changes to the file

.pre-commit-config.yaml, docs/api_reference/trestle.common.load_validate.md, mkdocs.yml, tests/trestle/core/commands/author/catalog_test.py, tests/trestle/core/commands/validate_test.py, trestle/common/load_validate.py, trestle/common/model_utils.py, trestle/core/catalog_interface.py, trestle/core/commands/assemble.py, trestle/core/commands/author/catalog.py, trestle/core/commands/author/jinja.py, trestle/core/commands/author/profile.py, trestle/core/commands/author/ssp.py, trestle/core/commands/href.py, trestle/core/commands/import_.py, trestle/core/links_validator.py, trestle/core/repository.py
Catalog group id's are optional so now create ids for any groups missing id's on import and give warning
Fixed bug counting links and references during validation
Added new load_validate.py file to validate files during load - which will also create group id's if needed
Then replaced all functions like load_top_level... to use the load_validate instead.
=> fix: allow catalog groups with no id and fix validation of links and reference matching

tests/trestle/core/commands/author/docs_test.py, tests/trestle/core/commands/author/versioning/template_versioning_test.py, trestle/core/commands/author/versioning/template_versioning.py
Don't create empty `0.0.1` if not necessary when running `trestle docs validate`
Also small code refactoring
Closes #1083
=> fix: Don't recreate 0.0.1 folder when running `trestle docs validate`

tests/trestle/core/commands/author/profile_test.py, trestle/core/commands/author/profile.py
- Fixed adding the section in markdown to the control that previously had no alters - now new alter is added.
- Fixed that deleting last section left empty alters for the control - now such alter is deleted completely.
=> fix: Handle adding/deleting section from the markdown control

trestle/core/commands/author/ssp.py, trestle/core/profile_resolver.py, trestle/core/resolver/_import.py, trestle/core/resolver/modify.py
Signed-off-by: Frank Suits <frankst@au1.ibm.com>
Prior to this change, any time a profile is resolved there will be warnings for params that do not have assigned values.  This is expected in many resolution contexts except when generating a final ssp - where missing values would mean the ssp is not complete.
Added new show_value_warnings to the profile resolution pipeline so that warnings are only emitted during profile resolution for ssp commands.
closes #1170
=> fix: only show missing value warnings when resolving a profile for ssp

tests/trestle/core/commands/author/profile_test.py, trestle/common/file_utils.py, trestle/core/control_reader.py
A single alter->add is created for parts and props rather than two separate ones
closes #1169
=> fix: combine parts props into a single add rather than two separate ones

tests/data/json/profile_with_alter_props.json, tests/trestle/core/commands/author/profile_test.py, trestle/core/commands/author/profile.py, trestle/core/control_writer.py
the default ns was being output.
new behavior is never to output the default ns into markdown
=> fix: prevent output of default namespace in markdown

tests/data/json/profile_with_alter_props.json, tests/data/json/simple_test_profile.json, tests/data/json/simplified_nist_catalog.json, tests/trestle/core/commands/author/catalog_test.py, tests/trestle/core/commands/author/profile_test.py, tests/trestle/core/commands/author/ssp_test.py, tests/trestle/core/profile_resolver_test.py, trestle/common/common_types.py, trestle/common/const.py, trestle/core/catalog_interface.py, trestle/core/control_interface.py, trestle/core/control_reader.py, trestle/core/control_writer.py
There was confusion on the headers Part and Control during profile assemble
This was cleared up, and parts at the control level are positioned after the control statement with header Control.
Parts bound to a sub-part of the statement are labeled Part
closes #1175
closes #1178
=> fix: parts labeled Control should be Part

tests/data/jinja/profile_to_docs_with_subparts.md.jinja, tests/data/json/profile_with_alter_subparts.json, tests/trestle/core/commands/author/jinja_cmd_test.py, trestle/common/const.py, trestle/core/control_interface.py, trestle/core/control_writer.py, trestle/core/docs_control_writer.py
- Added subparts to the part info returned by `ControlInterface`
- Added subparts to the markdown docs.
- Allowed subparts to be renamed via Jinja template.
Closes #1164
=> fix: Add subparts to the markdown docs

tests/data/json/profile_with_alter_subparts.json, tests/trestle/core/commands/author/jinja_cmd_test.py, tests/trestle/core/commands/author/profile_test.py, trestle/core/control_reader.py
If a part was added to a statement part it was added with name "item" but it should be the normal part name.
Adjusted the test profile for jinja to represent a statement part with a subpart.
closes #1183 
=> fix: name of subparts added into statement should not be "item"

tests/data/jinja/profile_to_docs.md.jinja, tests/data/jinja/profile_to_docs_only_some_sections.md.jinja, tests/data/jinja/profile_to_docs_with_group_title.md.jinja, tests/data/jinja/profile_to_docs_with_subparts.md.jinja, tests/data/json/test_profile_a.json, tests/trestle/core/commands/author/jinja_cmd_test.py, trestle/common/list_utils.py, trestle/core/catalog_interface.py, trestle/core/commands/author/jinja.py, trestle/core/docs_control_writer.py
- Fixed a bug where display-name for the parameters was pulled from the profile instead of the resolved catalog.
- Test that parts can be renamed via Jinja
=> fix: Pull display name from the resolved catalog

scripts/resolve_profile_catalog.py, tests/data/json/test_profile_b.json, tests/test_utils.py, tests/trestle/core/commands/author/profile_test.py, tests/trestle/core/profile_resolver_test.py, trestle/common/const.py, trestle/core/commands/author/catalog.py, trestle/core/commands/author/profile.py, trestle/core/control_interface.py, trestle/core/control_reader.py, trestle/core/control_writer.py, trestle/core/profile_resolver.py, trestle/core/resolver/modify.py
Previously profile-assemble would add control sections as parts 'after' the statement.  Now they are just added as 'ending' and with no by_id.
Added script to generate resolved profile catalog
Assign correct oscal version in assembled catalog and profile
Changed metadata title and href in resolved profile catalogs
closes #1181 
closes #1188
Added script to create resolved profile catalog from profile.
=> fix: profile assemble 'after' and 'by-id' issue, and added resolve_profile_catalog script

tests/trestle/core/commands/author/jinja_cmd_test.py, tests/trestle/core/control_io_test.py, tests/trestle/core/profile_resolver_test.py, trestle/core/catalog_interface.py, trestle/core/commands/author/jinja.py, trestle/core/control_interface.py, trestle/core/docs_control_writer.py, trestle/core/resolver/modify.py
Provided new ASSIGNMENT_FORM parameter rep and made it default for the jinja output of the resolved profile catalog
Refactored functions from Modify to ControlInterface and made some functions public
=> feat: added new parameter rep ASSIGNMENT_FORM to leave params in brackets with text

tests/trestle/core/commands/author/profile_test.py, trestle/core/commands/author/profile.py
For CLI profile-resolve command, default mode is now to leave moustaches in prose
=> fix: prof resolve should use moustache form as default

tests/trestle/core/commands/author/component_test.py, trestle/core/commands/author/component.py
component-generate was not generating proper header content when profile was not specified
fixed bug and expanded test coverage
Note this is intended to merge into the inherited props pr
=> fix: component generate will use sources in components if profile not specified

tests/trestle/core/commands/author/profile_test.py, trestle/core/commands/author/profile.py
If -sv is specified to output the value during profile-resolve, a new parameter -bf --bracket-format allows specifying brackets around that value
closes #1206 
=> feat: allow profile-resolve to specify brackets around value

tests/data/json/comp_def.json, tests/trestle/core/commands/author/component_test.py, trestle/common/const.py, trestle/common/model_utils.py, trestle/core/catalog_interface.py, trestle/core/commands/author/component.py, trestle/core/control_context.py, trestle/core/control_interface.py, trestle/core/control_reader.py, trestle/core/control_writer.py, trestle/core/generic_oscal.py
Put profile title in comp-gen markdown
Removed -profile option from command
Reworked component-generate to conform to new naming conventions
Changed allowed vals for imp_status
closes #1205 
=> fix: add profile title to comp-generate md and remove profile option

tests/data/json/test_profile_f.json, tests/trestle/core/commands/author/profile_test.py, trestle/common/const.py, trestle/core/catalog_interface.py
Bad break statement killed part label lookup needed for smt-part: a. in yaml header added prop
closes #1212
=> fix: simple fix for statement labels not showing properly

tests/trestle/core/utils_test.py, tests/trestle/core/validator_helper_test.py, trestle/common/model_utils.py, trestle/core/commands/author/component.py, trestle/core/resolver/merge.py
Improved the check for model equivalence to recurse and check every attribute except specified ones.
Converted references to __field_set__ to __field__ because field_set only pertains to fields set when the obect was first initialized.  other fields could be set later and they would be missed.
=> feat: made model equivalence check more rigorous

tests/trestle/core/commands/author/catalog_test.py, trestle/core/catalog_interface.py
Per recent feature request - simple routine in catalog_interface to get control statement prose as list of indented items.
=> feat: get statement parts to allow easy capture of statement prose

docs/cli.md, tests/trestle/core/commands/init_test.py, trestle/common/const.py, trestle/core/commands/init.py
Added new modes to `trestle init`. Now it can be run in three different modes: full, local and govdocs.
Full mode is identical to current Trestle init
Local mode will not create dist folder
Govdocs mode will only create .trestle folder
#Closes #1218
=> feat: Allow trestle init to specify the purpose of initialisation

tests/data/json/simplified_nist_catalog.json, tests/trestle/core/commands/author/catalog_test.py, tests/trestle/core/utils_test.py, trestle/core/catalog_interface.py
Small change so that get_statement_parts provides the top level prose for the statement
=> fix: add top level to parts output by get_statement_parts

.github/workflows/python-push.yml
Pre-commit uses a new version of the `importlib-metadata` for the Python 3.7 which causes `make code-lint` to fail.
This is a quick fix to use python 3.8 for the release instead.
=> fix: Use python 3.8 for the release

.pre-commit-config.yaml, trestle/core/models/elements.py
Gitlab repo of flake8 has been removed and project is now hosted on Github. 
Updated a version of flake8 used in pre-commit to Github repo
=> fix: Bump flake8 in pre-commit configuration

docs/cli.md, docs/python_trestle_setup.md, docs/trestle_author.md, docs/tutorials/ssp_profile_catalog_authoring/ssp_profile_catalog_authoring.md, docs/tutorials/task.ocp4-cis-profile-to-oscal-catalog/transformation.md, docs/tutorials/task.ocp4-cis-profile-to-oscal-cd/transformation.md, docs/tutorials/task.tanium-result-to-oscal-ar/transformation.md, docs/tutorials/task.transformer-construction/transformer-construction.md, docs/tutorials/trestle_sample_workflow.md, mkdocs.yml
Fixed html markdown in the documentation.
Rearranged the documentation and added tabs.
=> fix: Fix html markdown blocks in documentation

tests/trestle/core/commands/author/docs_test.py, trestle/core/commands/author/docs.py, trestle/core/markdown/markdown_api.py, trestle/core/markdown/markdown_processor.py, trestle/core/markdown/markdown_validator.py
Currently `docs template-validate` would validate header and body by default, however only the body should be validated if no flags are provided. Header should be validated only when `-hv` or `-hov` are provided.
This PR fixes the issue.
=> fix: Fix docs template validate flags

setup.cfg
Removing pinning of `attrs` version, as there seems to be no breaking dependency. 
I have tested this tested this using poetry command. Given below is the output of 
`poetry show attrs` command.
```python
name         : attrs
version      : 22.2.0
description  : Classes Without Boilerplate
required by
- jsonschema >=17.4.0
- pytest >=17.4.0
```
I am recommending this change, as pinned version of `attrs` package is causing my dependency conflicts.
=> fix: Remove attrs version pinning

tests/trestle/core/profile_resolver_test.py, trestle/core/remote/cache.py, trestle/core/resolver/_import.py
If you try to resolve a profile at a remote url, and its href to the catalog is local to its directory - it will fail.  This has now been updated so that it works.
closes #1287 
=> feat: allow remote profiles to reference catalogs and profiles by relative path in href

tests/conftest.py, tests/trestle/core/commands/author/catalog_test.py, trestle/core/catalog/catalog_api.py, trestle/core/catalog/catalog_interface.py, trestle/core/catalog/catalog_reader.py
cat-assemble wasn't capturing sub group names properly
closes #1289 
=> fix: problem in cat assemble with subgroups

docs/tutorials/ssp_profile_catalog_authoring/ssp_profile_catalog_authoring.md, scripts/gen_oscal.py, tests/data/json/comp_def_a.json, tests/trestle/core/commands/author/component_test.py, trestle/common/const.py, trestle/core/control_interface.py, trestle/core/control_reader.py, trestle/core/control_writer.py
The code was not allowing edit of rule parameter values during component-generate and component-assemble.  This is now working properly and has a corresponding test.
closes #1297
=> fix: allow edit of rule param values during component assemble

tests/trestle/core/commands/author/component_test.py
Increase coverage for comp generate and assemble and confirm edits work as expected
closes #1277
=> fix: boost test coverage for component generate and assemble

tests/data/json/comp_prof_ab.json, tests/trestle/core/commands/author/component_test.py, tests/trestle/core/commands/author/ssp_test.py, trestle/common/log.py, trestle/core/catalog/catalog_interface.py, trestle/core/catalog/catalog_writer.py, trestle/core/control_interface.py
Now give warnings if component references control not loaded by profile during ssp-gen and comp-gen
=> fix: Give warnings when component references control not loaded by profile for comp-gen and ssp-gen

.github/workflows/codeql-analysis.yml
codeql v1 is deprecated and need to switch to v2
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
=> fix: codeql update from v1 to v2

docs/api_reference/trestle.core.markdown.base_markdown_node.md, docs/api_reference/trestle.core.markdown.control_markdown_node.md, docs/api_reference/trestle.core.markdown.docs_markdown_node.md, docs/api_reference/trestle.core.markdown.markdown_node.md, mkdocs.yml, tests/trestle/core/commands/author/jinja_cmd_test.py, tests/trestle/core/commands/author/profile_test.py, tests/trestle/core/control_io_test.py, tests/trestle/core/markdown/markdown_node_test.py, tests/trestle/core/ssp_io_test.py, trestle/core/control_reader.py, trestle/core/jinja.py, trestle/core/markdown/base_markdown_node.py, trestle/core/markdown/control_markdown_node.py, trestle/core/markdown/docs_markdown_node.py, trestle/core/markdown/markdown_processor.py, trestle/core/markdown/markdown_validator.py, trestle/core/remote/cache.py, trestle/core/ssp_io.py
A first part of refactoring control_reader.py. 
Currently this change **only affects catalog** functionality.
Features:
1. Added a new type of markdown node: `ControlMarkdownNode` to separate the functionality needed for governed documents and Trestle core.
2. Rewrote the reading of control parts: statement, guidance, objective and extra.
3. Added an interface to fetch control parts from the tree (see changes to `control_reader.read_control` for example)
4. Deleted no longer needed code from control_reader, and moved the legacy code to `ControlMarkdownNode`
Things left to do for part 2
1. Reading of Editable content is still read by control_reader
2. Legacy code for reading subparts of a part needs further refactoring 
3. Further control_reader refactoring to put all code into …
=> chore: Refactoring of control reader to a new type of markdown node (Part 1)

trestle/core/commands/author/ssp.py
ssp-assemble was including files referenced by comp defs but not included in the ssp profile.  This has been changed so that only controls included in the profile will end up in the assembled json ssp.
=> fix: ssp assemble includes controls not in the profile

tests/conftest.py, tests/trestle/core/commands/validate_test.py, trestle/core/duplicates_validator.py
duplicate validator was failing for ssp and compdef if duplicate param_ids were found.  
closes #1339 
=> fix: duplicate param_id should be invalid only in profile

trestle/core/commands/author/ssp.py
Quieted confusing message about system component statuses set to operational during ssp assemble.  They are now quietly set to operational as default.  The markdown captures status of implementations but not the status of the components themselves.
=> fix: quiet warning about system component status as operational

docs/cli.md, docs/tutorials/continuous-compliance/continuous-compliance.md, docs/tutorials/task.transformer-construction/transformer-construction.md
Commensurate with #1329 update docs to specify renamed task xccdf-result-to-oscal-ar.
=> fix: docs for task xlsx-result-to-oscal-ar replacing "osco"

tests/trestle/tasks/csv_to_oscal_cd_test.py, trestle/tasks/csv_to_oscal_cd.py
=> fix: parameter value default is never required

tests/trestle/tasks/csv_to_oscal_cd_test.py, trestle/tasks/csv_to_oscal_cd.py
=> feat: support validation component_type for task csv-to-oscal-cd

tests/trestle/tasks/csv_to_oscal_cd_test.py, trestle/tasks/csv_to_oscal_cd.py
1. do not add duplicate set-parameter name when value is same as existing one
2. error if adding set-parameter with same name but different value
=> fix: prevent duplicates in set-parameters

tests/trestle/core/commands/author/profile_test.py, tests/trestle/core/commands/author/ssp_test.py, trestle/common/const.py, trestle/common/model_utils.py, trestle/core/catalog/catalog_reader.py, trestle/core/catalog/catalog_writer.py, trestle/core/commands/author/profile.py, trestle/core/remote/cache.py, trestle/transforms/implementations/xccdf.py
=> fix: parameter aggregation fix

tests/trestle/tasks/csv_to_oscal_cd_test.py, trestle/tasks/csv_to_oscal_cd.py
=> fix: improve bad property error message by including csv row number

docs/trestle_author.md
This documentation is related to issue #1464 about _**enabling validate template type parameter for trestle author docs command**_
=> docs: updating vtt documentation for trestle author docs

tests/data/json/full_profile_rev5.json, tests/trestle/core/commands/import__test.py, tests/trestle/core/profile_resolver_test.py
Updates the remote references to NIST `oscal-content` repository in tests to a commit.
=> fix(tests): pins oscal-content references in tests the latest 1.0 commit

tests/data/tasks/xccdf/input-oscap-arf-results/results_arf.xml, tests/data/tasks/xccdf/input-oscap-results/results.xml, tests/data/tasks/xccdf/output-oscap-arf-results/results_arf.oscal.json, tests/data/tasks/xccdf/output-oscap-results/results.oscal.json, tests/data/tasks/xccdf/test-xccdf-result-to-oscal-ar-input-oscap-arf-results.config, tests/data/tasks/xccdf/test-xccdf-result-to-oscal-ar-input-oscap-results.config, tests/trestle/tasks/xccdf_result_to_oscal_ar_test.py, trestle/transforms/implementations/xccdf.py
- [x ] New feature (non-breaking change which adds functionality)
Before this commit if you wanted to use result files from OpenSCAP in the task xccdf_result_to_oscal_ar you had to extract the `TestResult` element and place it as the root of the XML document, otherwise the resulting OSCAL document would be blank. Thus making it impossible to directly use output from OpenSCAP with the task.
With this commit the task will detect that the root element is not `TestResult` and then it will find the `TestResult` element in the XML document. This allows the use of files created by OpenSCAP using the `--results` and `--results-arf` switches.
Fixes #1410
- Ensure CI is …
=> feat: allow use of OpenSCAP result files in task xccdf_result_to_oscal_ar

tests/data/json/full_profile_rev5.json, tests/data/json/test_compdef_rev5.json, tests/test_utils.py, tests/trestle/core/commands/author/ssp_test.py, trestle/core/catalog/catalog_interface.py, trestle/core/catalog/catalog_reader.py
Updates Catalog Interface `get_statement_part_id_map ` to check if the label is empty. If the label is empty and `label_as_key` is True, the statement is not added to the map.
This may be only a partial fix because any statement that does not have a label property would be skipped over here.
Test added to verify the fix
Some alternatives fixes I tried.
- If a label does not existing for a statement part, set it to the part id. This broke several unit tests.
- Changing the the convention that an empty label means adding it to the implemented requirement, but this also broke several unit tests.
Fixes #1502 
- Check sonar. If you are …
=> fix: add check for empty label to fix failure for statement with no label property

README.md, trestle/core/catalog/catalog_interface.py
Updates Community meeting details in README.md
=> docs: updates communication details in README.md

tests/trestle/core/commands/author/versioning/template_versioning_test.py, trestle/core/commands/author/versioning/template_versioning.py
Resolved #1586 
Correct the regex of the template version to prevent an invalid version format
=> fix: update the regex of template version to prevent invalid version format

setup.cfg, trestle/core/repository.py
Fixes [Issue #1562](https://github.com/oscal-compass/compliance-trestle/issues/1562)
Optional string parameters should have a default value of `None` instead of empty string.
=> fix: default value for optional string params should be None

MAINTAINERS.md
Removes inactive maintainers from `MAINTAINERS.md`
=> docs: update maintainers list to reflect active maintainers

.github/workflows/python-test.yml
Dependabot does not have access to secrets and the updates only include third party dependency updates and should not need sonar scans.
Closes #1655 
=> fix: skips sonar scans for dependabot updates

tests/trestle/tasks/cis_xlsx_to_oscal_catalog_test.py, trestle/tasks/cis_xlsx_to_oscal_catalog.py
=> fix: make status and mitre column optional

tests/data/json/profile_aggregation.json, tests/trestle/core/commands/author/ssp_test.py, trestle/core/catalog/catalog_writer.py, trestle/core/control_interface.py
Closes #1596 
I'm making this as a feature addition as we didn't initially considered this to be supported in SSP, just in profile.
=> feat: add parameter aggregation support for SSP

README.md, docs/index.md, docs/maintainers.md
https://github.com/cncf/foundation/blob/main/website-guidelines.md
=> fix: lf footer website guidelines

CONTRIBUTING.md
=> fix: add Python coding standards info

docs/api_reference/trestle.core.jinja.base.md, docs/api_reference/trestle.core.jinja.ext.md, docs/api_reference/trestle.core.jinja.filters.md, docs/api_reference/trestle.core.jinja.md, docs/api_reference/trestle.core.jinja.tags.md, docs/api_reference/trestle.core.plugins.md, docs/contributing/plugins.md, docs/trestle_author_jinja.md, mkdocs.yml, tests/conftest.py, tests/trestle/core/jinja/filters_test.py, tests/trestle/core/jinja/tags_test.py, tests/trestle/core/jinja_filters_test.py, trestle/cli.py, trestle/core/commands/author/jinja.py, trestle/core/jinja/__init__.py, trestle/core/jinja/base.py, trestle/core/jinja/ext.py, trestle/core/jinja/filters.py, trestle/core/jinja/tags.py, trestle/core/jinja_filters.py, trestle/core/plugins.py
Builds on the proof of concept at #1684 and:
* moves the methods in the previously new `ssp_interface` into a set of jinja filters. Example switch in use:
`{% for party in ssp_interface.get_parties_for_role(ssp.metadata.responsible_parties, "prepared-by") %}` becomes
`{% for party in ssp.metadata.responsible_parties | parties_for_role("prepared-by", ssp) %}`
`{{ ssp_interface.safe_retrieval(address, 'addr_lines', []) | join(' ') }}` becomes `{{ address.addr_lines | as_list | join(' ') }}`
* refactors the jinja code into a module to better organize it and avoid some circular dependencies
* enables loading extensions from plugins, searching under: `trestle_{plugin_name}.jinja_ext`
* updates plugin docs
- #1719 
- …
=> feat(author-jinja): load jinja extensions from plugins

pyproject.toml
Semantic release is running in a container that does not have access to the dependencies installed in `make develop` step. This just adds the command run with the `make develop` target as part of the build.
=> fix(build): installs required build dependencies during semantic release

docs/tutorials/Transformers_and_Tasks/csv_to_oscal_cd.md, docs/tutorials/Transformers_and_Tasks/csv_to_oscal_cd/rule-name-overlap.csv
=> fix: add example csv for multiple rules and checks

CONTRIBUTING.md
=> fix: explain code quality checks in contribution guide

.github/workflows/docs-update.yml, .github/workflows/python-push.yml, mkdocs.yml, setup.cfg
This PR does two things:
1. Decouples documentation build from the build of the actual codebase
2. Introduces versioning at the `major.minor` level for the documentation website.
Once this PR works and runs through a release cycle the intent would be to further decouple the release to minimise issues associated with build changes (e.g. credential expiry; flaky access etc).
Closes: #1547 
=> feat: decouple docs release and introduce versioning

.github/CODEOWNERS, CONTRIBUTING.md
Following this merge the branch ruleset will be updated to require CODEOWNERS approval for merge.
Partially closes #1716 
Documentation on the structure and use of CODEOWNERS is available - https://github.com/oscal-compass/community/pull/70 and will be merged after acceptance.
=> chore: add initial CODEOWNERS file

tests/trestle/core/control_io_test.py, trestle/core/catalog/catalog_interface.py, trestle/core/control_interface.py, trestle/core/control_writer.py, trestle/transforms/implementations/tanium.py
=> fix: merge control markdown with json (#1528)

.github/workflows/docs-update.yml, scripts/mike_version_parse.py
Fixes that the required script was missing. We all miss this in review (whoops)
=> fix: correct missing script

.github/workflows/docs-update.yml, .github/workflows/python-test.yml, CONTRIBUTING.md
This PR fixes the two pipeline failures:
- [Docs update](https://github.com/oscal-compass/compliance-trestle/actions/runs/12120880496)
- GITHUB_REF is [not available through the env context](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables). Switching to `github.event.ref`.
- Dead link on the `python-semantic-release` docs site
Adds (**If this add does not seem super valuable, I can remove from this PR**)
~~- A check in python test workflow where the mike-version script is checked against the environment.~~
The `mike-version` job should pass
```bash
act push -e test-event.json -W .github/workflows/docs-update.yml
```
test-event.json contains
```bash
{
"ref": "refs/tags/v3.6.0"
}
```
- [Sonar …
=> ci: fixes pipeline failures in docs

.github/workflows/docs-update.yml
Fixes issue found in GitHub Actions run - https://github.com/oscal-compass/compliance-trestle/actions/runs/12144416048
Tested with Action Lint - https://rhysd.github.io/actionlint/
1. Documentation dependencies should pass
2. The create release step should run
I could not fully validate to due permissions issues.
```bash
act push -e test-event.json -W .github/workflows/docs-update.yml -j deploy-docs
```
test-event.json contains
```bash
{
"ref": "refs/tags/v3.6.0"
}
```
=> fix: adds outputs context to mike-version output

.gitmodules, Makefile, README.md, docs/contributing/website.md, release-schemas/oscal_assessment-plan_schema.json, release-schemas/oscal_assessment-results_schema.json, release-schemas/oscal_catalog_schema.json, release-schemas/oscal_complete_schema.json, release-schemas/oscal_component_schema.json, release-schemas/oscal_poam_schema.json, release-schemas/oscal_profile_schema.json, release-schemas/oscal_ssp_schema.json, scripts/gen_oscal.py, scripts/oscal_normalize.py, tests/data/json/simple_test_profile2.json, tests/test_utils.py, tests/trestle/core/commands/author/prof_test.py, tests/trestle/tasks/ocp4_cis_profile_to_oscal_cd_test.py, tests/trestle/tasks/xlsx_to_oscal_cd_test.py, tests/trestle/tasks/xlsx_to_oscal_profile_test.py, trestle/core/control_writer.py, trestle/oscal/__init__.py, trestle/oscal/common.py, trestle/tasks/cis_xlsx_to_oscal_catalog.py
=> chore: trestle release 3.8.0

SECURITY-INSIGHTS.yml
Adds an initial [OpenSSF Security Insights](https://github.com/ossf/security-insights-spec/tree/v2.0.0) file.
Reported as missing by [CLOMonitor](https://clomonitor.io/projects/cncf/oscal-compass#compliance-trestle_security).
=> docs: add OpenSSF Security Insights file

tests/test_utils.py, tests/trestle/core/ssp_io_test.py, trestle/core/ssp_io.py
=> fix: don't skip main component when creating SSP with author jinja

.github/security-insights.yml
Moves security insights file under `.github` and removes project level information. Project level information will be stored in the `.github` repo.
=> docs: updates security insights location and content

pyproject.toml, setup.cfg
This PR moves the project metadata and dependencies from `setup.cfg` to `pyproject.toml`.   This can be tested directly by running `pip install .` and  `pip install ".[dev]"` (for optional dev dependencies).
Closes https://github.com/oscal-compass/compliance-trestle/issues/1851
=> feat: move dependencies from setup.cfg to pyproject.toml

CONTRIBUTING.md, pyproject.toml, tests/data/author/catalogs/NIST-SP800-218-ver1-selected/catalog.json, tests/trestle/core/commands/assemble_test.py, trestle/common/str_utils.py, trestle/core/markdown/control_markdown_node.py
=> fix: bad part name/id when generate/assemble markdown
